# 09_00 EES Uncertainty and Rank Stability

## Reviewer-facing purpose
This notebook addresses the remaining uncertainty gap identified by the reviewers: **are the EES component scores, composite EES values, and resulting model rankings sensitive to the particular 80/20 train-test partition used in the primary analysis?**

It performs **20 repeated stratified 80/20 holdout evaluations**. Only the train-test partition changes. Model families, fixed hyperparameters, EES definitions, corrected Regulatory Alignment, and primary equal EES weights remain unchanged.

This first version is configured for **German Credit**. It recomputes Fidelity, Stability, Counterfactual Actionability, Regulatory Alignment, EES, and rank for every repetition, then reports empirical score uncertainty and rank stability.

In [1]:
# 0. Install and import
!pip -q install shap lime dice-ml xgboost openpyxl
import warnings; warnings.filterwarnings('ignore')
from pathlib import Path
from datetime import datetime
import json, random, time, re
import numpy as np, pandas as pd
from scipy.stats import kendalltau
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, RobustScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier
import shap
from lime.lime_tabular import LimeTabularExplainer
import dice_ml
pd.set_option('display.max_columns',250)
pd.set_option('display.float_format',lambda x:f'{x:.6f}')

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.7/275.7 kB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 18.1 MB/s eta 0:00:00
  Building wheel for lime (setup.py) ... done

In [2]:
# 1. Locked configuration
DATASET_NAME='german_credit'; DATASET_LABEL='German Credit'
N_REPETITIONS=20; TEST_SIZE=0.20
SPLIT_SEEDS=list(range(42,62))
KERNEL_BACKGROUND_SIZE=50; KERNEL_NSAMPLES=500
LIME_NUM_SAMPLES=5000; LIME_NUM_FEATURES=10
N_PERTURBATIONS=30; PERTURBATION_STD=0.05
TOTAL_CFS=3; DICE_METHOD='random'; UNFAVOURABLE_CLASS=1; DESIRED_CLASS=0
IMMUTABLE_FEATURES=['Age','Sex']
REGULATORY_ALIGNMENT_SCORE=1.0
EES_WEIGHTS={'fidelity_score':.25,'stability_score':.25,'actionability_score':.25,'regulatory_alignment_score':.25}
print(SPLIT_SEEDS)

[42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61]

In [3]:
# 2. Drive and paths
from google.colab import drive
drive.mount('/content/drive')
ROOT_PATH=Path('/content/drive/MyDrive/Master_Research')
PREPROCESSING_DATASETS_PATH=ROOT_PATH/'07_Results'/DATASET_NAME/'02_data_preprocessing_german_credit'/'datasets'
RESULTS_PATH=ROOT_PATH/'07_Results'/DATASET_NAME/'09_00_ees_uncertainty_rank_stability'
TABLES_PATH=RESULTS_PATH/'tables'; DATASETS_PATH=RESULTS_PATH/'datasets'; LOGS_PATH=RESULTS_PATH/'logs'
for p in [RESULTS_PATH,TABLES_PATH,DATASETS_PATH,LOGS_PATH]: p.mkdir(parents=True,exist_ok=True)
print('Input:',PREPROCESSING_DATASETS_PATH); print('Output:',RESULTS_PATH)

Mounted at /content/drive
Input: /content/drive/MyDrive/Master_Research/07_Results/german_credit/02_data_preprocessing_german_credit/datasets
Output: /content/drive/MyDrive/Master_Research/07_Results/german_credit/09_00_ees_uncertainty_rank_stability

In [4]:
# 3. Helpers
def first_existing(folder,names,label):
    for name in names:
        p=folder/name
        if p.exists(): print(label,':',p); return p
    raise FileNotFoundError(label+' not found. Checked:\n'+'\n'.join(str(folder/n) for n in names))
def load_target(path):
    df=pd.read_csv(path)
    if 'target' in df.columns:return df['target'].astype(int)
    if df.shape[1]==1:return df.iloc[:,0].astype(int)
    raise ValueError('Target not identifiable')
def save_df(df,name,folder=TABLES_PATH):
    p=folder/name; df.to_csv(p,index=False); print('Saved:',p); return p
def predict_positive(model,X): return np.asarray(model.predict_proba(X))[:,1]
def inverse_minmax(v):
    v=np.asarray(v,float); lo,hi=np.nanmin(v),np.nanmax(v)
    return np.ones_like(v) if np.isclose(hi,lo) else (hi-v)/(hi-lo)
def safe_tau(a,b):
    if len(a)<2:return 0.0
    t=kendalltau(a,b,nan_policy='omit').statistic
    return 0.0 if pd.isna(t) else float(t)
def clean_lime_name(rule,names):
    m=[f for f in names if f in str(rule)]
    return max(m,key=len) if m else str(rule)
def make_models(seed):
    return {
      'logistic_regression':('Logistic Regression',LogisticRegression(solver='lbfgs',max_iter=2000,random_state=seed)),
      'decision_tree':('Decision Tree',DecisionTreeClassifier(max_depth=5,random_state=seed)),
      'random_forest':('Random Forest',RandomForestClassifier(n_estimators=300,random_state=seed)),
      'xgboost':('XGBoost',XGBClassifier(n_estimators=300,learning_rate=.05,max_depth=3,subsample=.9,colsample_bytree=.9,eval_metric='logloss',random_state=seed,n_jobs=-1)),
      'mlp':('MLP',MLPClassifier(hidden_layer_sizes=(50,),activation='relu',solver='adam',alpha=.0001,max_iter=1000,random_state=seed))}

In [5]:
# 4. Reconstruct full original-space modelling dataset from locked preprocessing outputs
xf1=first_existing(PREPROCESSING_DATASETS_PATH,['X_train_model_original.csv','X_train_original.csv'],'Train features')
xf2=first_existing(PREPROCESSING_DATASETS_PATH,['X_test_model_original.csv','X_test_original.csv'],'Test features')
yf1=first_existing(PREPROCESSING_DATASETS_PATH,['y_train.csv'],'Train target')
yf2=first_existing(PREPROCESSING_DATASETS_PATH,['y_test.csv'],'Test target')
X_full=pd.concat([pd.read_csv(xf1),pd.read_csv(xf2)],ignore_index=True).drop(columns=['target'],errors='ignore')
y_full=pd.concat([load_target(yf1),load_target(yf2)],ignore_index=True)
assert len(X_full)==len(y_full)
print(X_full.shape); display(y_full.value_counts(normalize=True).sort_index())

Train features : /content/drive/MyDrive/Master_Research/07_Results/german_credit/02_data_preprocessing_german_credit/datasets/X_train_original.csv
Test features : /content/drive/MyDrive/Master_Research/07_Results/german_credit/02_data_preprocessing_german_credit/datasets/X_test_original.csv
Train target : /content/drive/MyDrive/Master_Research/07_Results/german_credit/02_data_preprocessing_german_credit/datasets/y_train.csv
Test target : /content/drive/MyDrive/Master_Research/07_Results/german_credit/02_data_preprocessing_german_credit/datasets/y_test.csv
(1000, 10)

target
0   0.700000
1   0.300000
Name: proportion, dtype: float64

In [6]:
# 5. Locked German Credit preprocessing
CATEGORICAL_FEATURES=[c for c in ['Sex','Job','Housing','Saving accounts','Checking account','Purpose'] if c in X_full.columns]
NUMERIC_FEATURES=[c for c in X_full.columns if c not in CATEGORICAL_FEATURES]
def make_preprocessor():
    num=Pipeline([('imputer',SimpleImputer(strategy='median')),('scaler',RobustScaler())])
    cat=Pipeline([('imputer',SimpleImputer(strategy='constant',fill_value='Missing')),('onehot',OneHotEncoder(handle_unknown='ignore',sparse_output=False))])
    return ColumnTransformer([('num',num,NUMERIC_FEATURES),('cat',cat,CATEGORICAL_FEATURES)],remainder='drop')
print('Numeric:',NUMERIC_FEATURES); print('Categorical:',CATEGORICAL_FEATURES)

Numeric: ['original_index', 'Age', 'Credit amount', 'Duration']
Categorical: ['Sex', 'Job', 'Housing', 'Saving accounts', 'Checking account', 'Purpose']

## 6. Locked EES component logic
**Fidelity** is the equal mean of SHAP reconstruction fidelity, LIME local surrogate fidelity, and SHAP-LIME Kendall agreement. **Stability** uses 30 Gaussian perturbations (SD 0.05) per held-out observation and inverse min-max normalisation across the five models within each repetition. **Actionability** uses DiCE with 3 requested counterfactuals, desired class 0, and Age/Sex immutable. **Regulatory Alignment** remains 1.000 because all four corrected governance-evidence criteria are satisfied. The primary EES uses equal 0.25 weights.

In [7]:
# 6A. Fidelity
def shap_probability(estimator,Xtr,Xte,seed):
    rng=np.random.RandomState(seed); n=min(KERNEL_BACKGROUND_SIZE,len(Xtr)); bg=Xtr[rng.choice(len(Xtr),n,replace=False)]
    if isinstance(estimator,(DecisionTreeClassifier,RandomForestClassifier,XGBClassifier)):
        try:
            ex=shap.TreeExplainer(estimator,data=bg,feature_perturbation='interventional',model_output='probability')
            sv=ex.shap_values(Xte); ev=ex.expected_value
            if isinstance(sv,list): sv=sv[1]
            sv=np.asarray(sv)
            if sv.ndim==3: sv=sv[:,:,1]
            if isinstance(ev,(list,np.ndarray)): ev=np.asarray(ev).reshape(-1)[-1]
            return np.asarray(sv,float),float(ev)
        except Exception: pass
    f=lambda z:estimator.predict_proba(np.asarray(z))[:,1]
    ex=shap.KernelExplainer(f,bg); sv=ex.shap_values(Xte,nsamples=KERNEL_NSAMPLES,silent=True); ev=ex.expected_value
    if isinstance(sv,list): sv=sv[-1]
    sv=np.asarray(sv)
    if sv.ndim==3: sv=sv[:,:,-1]
    if isinstance(ev,(list,np.ndarray)): ev=np.asarray(ev).reshape(-1)[-1]
    return np.asarray(sv,float),float(ev)
def fidelity_for_model(estimator,Xtr,Xte,names,seed):
    sv,ev=shap_probability(estimator,Xtr,Xte,seed); p=predict_positive(estimator,Xte)
    shap_f=float(np.clip(1-np.mean(np.abs(p-(ev+sv.sum(axis=1)))),0,1))
    le=LimeTabularExplainer(Xtr,feature_names=list(names),class_names=['Non-default','Default'],mode='classification',random_state=seed)
    r2=[]; taus=[]
    for i in range(len(Xte)):
        exp=le.explain_instance(Xte[i],estimator.predict_proba,num_features=min(LIME_NUM_FEATURES,len(names)),num_samples=LIME_NUM_SAMPLES)
        r2.append(float(exp.score)); lm={}
        for rule,w in exp.as_list(label=1):
            f=clean_lime_name(rule,names)
            if f in names: lm[f]=abs(float(w))
        common=[f for f in names if f in lm]
        if len(common)>=2:
            sm={names[j]:abs(float(sv[i,j])) for j in range(len(names))}
            taus.append(safe_tau([sm[f] for f in common],[lm[f] for f in common]))
    lime=float(np.clip(np.nanmean(r2),0,1)); tau=float(np.nanmean(taus)) if taus else 0.0; agree=float(np.clip((tau+1)/2,0,1))
    return {'shap_reconstruction_fidelity_score':shap_f,'lime_fidelity_score':lime,'mean_kendall_tau':tau,'shap_lime_agreement_score':agree,'fidelity_score':float(np.mean([shap_f,lime,agree]))}

In [8]:
# 6B. Stability
def raw_stability(estimator,Xte,seed):
    rng=np.random.RandomState(seed); ratios=[]; changes=[]
    for x in Xte:
        x=np.asarray(x,float); p0=estimator.predict_proba(x.reshape(1,-1))[0,1]
        for _ in range(N_PERTURBATIONS):
            noise=rng.normal(0,PERTURBATION_STD,size=x.shape); norm=np.linalg.norm(noise)
            if norm<=0:continue
            pp=estimator.predict_proba((x+noise).reshape(1,-1))[0,1]; ch=abs(pp-p0)
            changes.append(ch); ratios.append(ch/norm)
    return {'mean_output_change':float(np.mean(changes)),'mean_local_lipschitz_ratio':float(np.mean(ratios))}

In [9]:
# 6C. Counterfactual Actionability
def impute_original(Xtr,Xte):
    a=Xtr.copy(); b=Xte.copy()
    for c in NUMERIC_FEATURES:
        med=pd.to_numeric(a[c],errors='coerce').median(); a[c]=pd.to_numeric(a[c],errors='coerce').fillna(med); b[c]=pd.to_numeric(b[c],errors='coerce').fillna(med)
    for c in CATEGORICAL_FEATURES:
        a[c]=a[c].astype(object).where(a[c].notna(),'Missing').astype(str); b[c]=b[c].astype(object).where(b[c].notna(),'Missing').astype(str)
    return a,b
def actionability(full_pipeline,Xtr,Xte,ytr,seed):
    tr,te=impute_original(Xtr,Xte); d=tr.copy(); d['target']=np.asarray(ytr,int)
    data=dice_ml.Data(dataframe=d,continuous_features=NUMERIC_FEATURES,outcome_name='target')
    dm=dice_ml.Model(model=full_pipeline,backend='sklearn',model_type='classifier'); de=dice_ml.Dice(data,dm,method=DICE_METHOD)
    pred=np.asarray(full_pipeline.predict(te),int); pos=np.where(pred==UNFAVOURABLE_CLASS)[0]
    mutable=[c for c in tr.columns if c not in IMMUTABLE_FEATURES]
    ranges={c:max(float(tr[c].max()-tr[c].min()),1e-12) for c in NUMERIC_FEATURES}
    found=[]; mind=[]; minchg=[]
    for k in pos:
        original=te.iloc[k]; query=te.iloc[[k]].copy()
        try:
            res=de.generate_counterfactuals(query,total_CFs=TOTAL_CFS,desired_class=DESIRED_CLASS,features_to_vary=mutable,random_seed=seed,verbose=False)
            cf=res.cf_examples_list[0].final_cfs_df
            if cf is None or cf.empty: found.append(0); continue
            found.append(1); cf=cf.drop(columns=['target'],errors='ignore'); ds=[]; cs=[]
            for _,r in cf.iterrows():
                ds.append(np.mean([abs(float(r[c])-float(original[c]))/ranges[c] for c in NUMERIC_FEATURES]))
                n=0
                for c in tr.columns:
                    try:same=np.isclose(float(original[c]),float(r[c]))
                    except:same=str(original[c])==str(r[c])
                    if not same:n+=1
                cs.append(n)
            mind.append(min(ds)); minchg.append(min(cs))
        except Exception: found.append(0)
    if len(pos)==0:return {'availability_score':np.nan,'proximity_score':np.nan,'sparsity_score':np.nan,'actionability_score':np.nan,'n_unfavourable_predictions':0}
    av=float(np.mean(found)); pr=float(np.clip(1-np.mean(mind),0,1)) if mind else 0.0; sp=float(np.clip(1-np.mean(minchg)/tr.shape[1],0,1)) if minchg else 0.0
    return {'availability_score':av,'proximity_score':pr,'sparsity_score':sp,'actionability_score':float(np.mean([av,pr,sp])),'n_unfavourable_predictions':int(len(pos))}

In [10]:
# 7. Run 20 repeated stratified 80/20 evaluations
all_rows=[]; run_log=[]
for repetition,seed in enumerate(SPLIT_SEEDS,1):
    print('\n'+'='*100); print(f'REPETITION {repetition}/{N_REPETITIONS} | seed={seed}'); print('='*100)
    started=time.time(); np.random.seed(seed); random.seed(seed)
    Xtr,Xte,ytr,yte=train_test_split(X_full,y_full,test_size=TEST_SIZE,stratify=y_full,random_state=seed)
    Xtr=Xtr.reset_index(drop=True); Xte=Xte.reset_index(drop=True); ytr=ytr.reset_index(drop=True); yte=yte.reset_index(drop=True)
    prep=make_preprocessor(); A=np.asarray(prep.fit_transform(Xtr),float); B=np.asarray(prep.transform(Xte),float)
    names=[f.replace('num__','').replace('cat__','') for f in prep.get_feature_names_out()]
    rep=[]
    for mid,(mname,est) in make_models(seed).items():
        print('  ',mname); est.fit(A,ytr)
        full=Pipeline([('preprocessor',prep),('classifier',est)])
        f=fidelity_for_model(est,A,B,names,seed); s=raw_stability(est,B,seed); a=actionability(full,Xtr,Xte,ytr,seed)
        rep.append({'dataset_name':DATASET_NAME,'dataset_label':DATASET_LABEL,'repetition':repetition,'split_seed':seed,'model_id':mid,'model_name':mname,**f,**s,**a,'regulatory_alignment_score':REGULATORY_ALIGNMENT_SCORE})
    rdf=pd.DataFrame(rep); rdf['stability_score']=inverse_minmax(rdf['mean_local_lipschitz_ratio'])
    rdf['ees_score']=.25*rdf['fidelity_score']+.25*rdf['stability_score']+.25*rdf['actionability_score']+.25*rdf['regulatory_alignment_score']
    rdf['ees_rank']=rdf['ees_score'].rank(method='min',ascending=False).astype(int)
    all_rows.extend(rdf.to_dict('records')); run_log.append({'repetition':repetition,'split_seed':seed,'elapsed_seconds':time.time()-started,'status':'completed'})
    pd.DataFrame(all_rows).to_csv(DATASETS_PATH/'ees_uncertainty_repetition_results_checkpoint.csv',index=False)
    display(rdf[['model_name','fidelity_score','stability_score','actionability_score','regulatory_alignment_score','ees_score','ees_rank']].sort_values('ees_rank'))
uncertainty_results_df=pd.DataFrame(all_rows); run_log_df=pd.DataFrame(run_log)
print('Rows:',len(uncertainty_results_df),'Expected:',N_REPETITIONS*5)

====================================================================================================
REPETITION 1/20 | seed=42
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.84it/s]
100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
100%|██████████| 1/1 [00:00<00:00,  3.26it/s]
100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
100%|██████████| 1/1 [00:00<00:00,  3.99it/s]
100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
100%|██████████| 1/1 [00:00<00:00,  4.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
100%|██████████| 1/1 [00:00<00:00,  5.07it/s]
100%|██████████| 1/1 [00:00<00:00,  4.67it/s]
100%|██████████| 1/1 [00:00<00:00,  4.89it/s]
100%|██████████| 1/1 [00:00<00:00,  4.94it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
100%|██████████| 1/1 [00:00<00:00,  2.92it/s]
100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
100%|██████████| 1/1 [00:00<00:00,  3.56it/s]
100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
100%|██████████| 1/1 [00:02<00:00,  2.07s/it]
100%|██████████| 1/1 [00:00<00:00,  4.67it/s]
100%|██████████| 1/1 [00:00<00:00,  5.06it/s]
100%|██████████| 1/1 [00:00<00:00,  5.04it/s]
100%|██████████| 1/1 [00:00<00:00,  5.05it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  2.67it/s]
100%|██████████| 1/1 [00:04<00:00,  4.60s/it]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.66it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:00<00:00,  2.34it/s]
100%|██████████| 1/1 [00:00<00:00,  1.77it/s]
100%|██████████| 1/1 [00:00<00:00,  1.86it/s]
100%|██████████| 1/1 [00:00<00:00,  1.80it/s]
100%|██████████| 1/1 [00:00<00:00,  1.86it/s]
100%|██████████| 1/1 [00:00<00:00,  1.86it/s]
100%|██████████| 1/1 [00:01<00:00,  1.08s/it]
100%|██████████| 1/1 [00:00<00:00,  1.75it/s]
100%|██████████| 1/1 [00:01<00:00,  1.30s/it]
100%|██████████| 1/1 [00:00<00:00,  2.76it/s]
100%|██████████| 1/1 [00:00<00:00,  2.76it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.71it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.68it/s]
100%|██████████| 1/1 [00:00<00:00,  1.29it/s]
100%|██████████| 1/1 [00:00<00:00,  2.77it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  1.12it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.67it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.79it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  1.76it/s]
100%|██████████| 1/1 [00:00<00:00,  1.86it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
100%|██████████| 1/1 [00:00<00:00,  6.21it/s]
100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
100%|██████████| 1/1 [00:00<00:00,  6.35it/s]
100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
100%|██████████| 1/1 [00:00<00:00,  6.27it/s]
100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  5.73it/s]
100%|██████████| 1/1 [00:00<00:00,  6.21it/s]
100%|██████████| 1/1 [00:00<00:00,  5.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.03it/s]
100%|██████████| 1/1 [00:00<00:00,  5.92it/s]
100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
100%|██████████| 1/1 [00:00<00:00,  6.51it/s]
100%|██████████| 1/1 [00:00<00:00,  6.61it/s]
100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
100%|██████████| 1/1 [00:00<00:00,  6.14it/s]
100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
100%|██████████| 1/1 [00:00<00:00,  6.61it/s]
100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
100%|██████████| 1/1 [00:00<00:00,  6.26it/s]
100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
100%|██████████| 1/1 [00:00<00:00,  6.35it/s]
100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
100%|██████████| 1/1 [00:00<00:00,  5.92it/s]
100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
100%|██████████| 1/1 [00:00<00:00,  3.38it/s]
100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
100%|██████████| 1/1 [00:00<00:00,  3.29it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  5.94it/s]
100%|██████████| 1/1 [00:00<00:00,  4.99it/s]
100%|██████████| 1/1 [00:00<00:00,  5.73it/s]
100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
100%|██████████| 1/1 [00:00<00:00,  5.70it/s]
100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
100%|██████████| 1/1 [00:00<00:00,  2.31it/s]
100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
100%|██████████| 1/1 [00:00<00:00,  5.70it/s]
100%|██████████| 1/1 [00:01<00:00,  1.21s/it]
100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  5.99it/s]
100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
100%|██████████| 1/1 [00:00<00:00,  2.83it/s]
100%|██████████| 1/1 [00:00<00:00,  6.03it/s]
100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  5.94it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
100%|██████████| 1/1 [00:00<00:00,  5.82it/s]
100%|██████████| 1/1 [00:00<00:00,  3.84it/s]
100%|██████████| 1/1 [00:00<00:00,  3.42it/s]
100%|██████████| 1/1 [00:00<00:00,  4.13it/s]
100%|██████████| 1/1 [00:00<00:00,  3.14it/s]
100%|██████████| 1/1 [00:00<00:00,  4.17it/s]
100%|██████████| 1/1 [00:00<00:00,  4.41it/s]
100%|██████████| 1/1 [00:00<00:00,  3.10it/s]
100%|██████████| 1/1 [00:00<00:00,  3.99it/s]
100%|██████████| 1/1 [00:00<00:00,  1.57it/s]
100%|██████████| 1/1 [00:00<00:00,  3.09it/s]
100%|██████████| 1/1 [00:00<00:00,  3.01it/s]
100%|██████████| 1/1 [00:00<00:00,  3.96it/s]
100%|██████████| 1/1 [00:00<00:00,  4.32it/s]
100%|██████████| 1/1 [00:00<00:00,  3.45it/s]
100%|██████████| 1/1 [00:00<00:00,  3.01it/s]
100%|██████████| 1/1 [00:00<00:00,  2.89it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  2.35it/s]
100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.60it/s]
100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
100%|██████████| 1/1 [00:00<00:00,  5.61it/s]
100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
100%|██████████| 1/1 [00:00<00:00,  5.27it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.826339,1.000000,0.936173,1.000000,0.940628,1
2,Random Forest,0.756394,0.978942,0.944807,1.000000,0.920036,2
1,Decision Tree,0.701840,0.918039,0.948544,1.000000,0.892106,3
4,MLP,0.567939,0.673061,0.946172,1.000000,0.796793,4
3,XGBoost,0.696672,0.000000,0.948515,1.000000,0.661297,5

====================================================================================================
REPETITION 2/20 | seed=43
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
100%|██████████| 1/1 [00:00<00:00,  3.44it/s]
100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.07it/s]
100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
100%|██████████| 1/1 [00:00<00:00,  6.06it/s]
100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
100%|██████████| 1/1 [00:00<00:00,  7.45it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
100%|██████████| 1/1 [00:00<00:00,  3.46it/s]
100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
100%|██████████| 1/1 [00:00<00:00,  3.78it/s]
100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
100%|██████████| 1/1 [00:00<00:00,  4.57it/s]
100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
100%|██████████| 1/1 [00:00<00:00,  4.00it/s]
100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
100%|██████████| 1/1 [00:00<00:00,  1.22it/s]
100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
100%|██████████| 1/1 [00:00<00:00,  7.65it/s]
100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
100%|██████████| 1/1 [00:00<00:00,  7.56it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  1.89it/s]
100%|██████████| 1/1 [00:00<00:00,  1.84it/s]
100%|██████████| 1/1 [00:00<00:00,  1.71it/s]
100%|██████████| 1/1 [00:00<00:00,  1.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.45it/s]
100%|██████████| 1/1 [00:00<00:00,  2.69it/s]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.75it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  1.65it/s]
100%|██████████| 1/1 [00:00<00:00,  1.14it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.71it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:07<00:00,  7.27s/it]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:00<00:00,  2.80it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.45it/s]
100%|██████████| 1/1 [00:00<00:00,  2.74it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.71it/s]
100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.58it/s]
100%|██████████| 1/1 [00:00<00:00,  2.77it/s]
100%|██████████| 1/1 [00:00<00:00,  2.45it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
100%|██████████| 1/1 [00:00<00:00,  6.04it/s]
100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
100%|██████████| 1/1 [00:00<00:00,  6.35it/s]
100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
100%|██████████| 1/1 [00:00<00:00,  6.31it/s]
100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
100%|██████████| 1/1 [00:00<00:00,  4.67it/s]
100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
100%|██████████| 1/1 [00:00<00:00,  3.89it/s]
100%|██████████| 1/1 [00:00<00:00,  2.87it/s]
100%|██████████| 1/1 [00:00<00:00,  4.60it/s]
100%|██████████| 1/1 [00:00<00:00,  3.47it/s]
100%|██████████| 1/1 [00:00<00:00,  4.12it/s]
100%|██████████| 1/1 [00:00<00:00,  3.72it/s]
100%|██████████| 1/1 [00:00<00:00,  3.08it/s]
100%|██████████| 1/1 [00:00<00:00,  2.90it/s]
100%|██████████| 1/1 [00:00<00:00,  2.94it/s]
100%|██████████| 1/1 [00:00<00:00,  2.92it/s]
100%|██████████| 1/1 [00:00<00:00,  2.86it/s]
100%|██████████| 1/1 [00:02<00:00,  2.81s/it]
100%|██████████| 1/1 [00:00<00:00,  2.38it/s]
100%|██████████| 1/1 [00:00<00:00,  4.57it/s]
100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
100%|██████████| 1/1 [00:00<00:00,  5.54it/s]
100%|██████████| 1/1 [00:00<00:00,  5.96it/s]
100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
100%|██████████| 1/1 [00:00<00:00,  6.07it/s]
100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
100%|██████████| 1/1 [00:00<00:00,  5.73it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
100%|██████████| 1/1 [00:00<00:00,  6.26it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  4.57it/s]
100%|██████████| 1/1 [00:00<00:00,  6.04it/s]
100%|██████████| 1/1 [00:00<00:00,  3.52it/s]
100%|██████████| 1/1 [00:00<00:00,  3.31it/s]
100%|██████████| 1/1 [00:00<00:00,  3.13it/s]
100%|██████████| 1/1 [00:00<00:00,  3.12it/s]
100%|██████████| 1/1 [00:00<00:00,  2.97it/s]
100%|██████████| 1/1 [00:00<00:00,  3.11it/s]
100%|██████████| 1/1 [00:00<00:00,  3.55it/s]
100%|██████████| 1/1 [00:00<00:00,  3.23it/s]
100%|██████████| 1/1 [00:00<00:00,  4.35it/s]
100%|██████████| 1/1 [00:00<00:00,  3.91it/s]
100%|██████████| 1/1 [00:00<00:00,  3.11it/s]
100%|██████████| 1/1 [00:00<00:00,  3.10it/s]
100%|██████████| 1/1 [00:00<00:00,  3.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.87it/s]
100%|██████████| 1/1 [00:00<00:00,  3.48it/s]
100%|██████████| 1/1 [00:00<00:00,  4.05it/s]
100%|██████████| 1/1 [00:00<00:00,  4.58it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  5.79it/s]
100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
100%|██████████| 1/1 [00:00<00:00,  3.46it/s]
100%|██████████| 1/1 [00:00<00:00,  5.98it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  4.81it/s]
100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
100%|██████████| 1/1 [00:00<00:00,  5.70it/s]
100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.61it/s]
100%|██████████| 1/1 [00:00<00:00,  4.85it/s]
100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
100%|██████████| 1/1 [00:00<00:00,  5.65it/s]
100%|██████████| 1/1 [00:00<00:00,  4.92it/s]
100%|██████████| 1/1 [00:00<00:00,  5.89it/s]
100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
100%|██████████| 1/1 [00:00<00:00,  5.70it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  5.73it/s]
100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
100%|██████████| 1/1 [00:00<00:00,  5.70it/s]
100%|██████████| 1/1 [00:00<00:00,  5.57it/s]
100%|██████████| 1/1 [00:00<00:00,  5.13it/s]
100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
100%|██████████| 1/1 [00:00<00:00,  5.70it/s]
100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
100%|██████████| 1/1 [00:00<00:00,  2.29it/s]
100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
100%|██████████| 1/1 [00:00<00:00,  4.78it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.805176,1.000000,0.929515,1.000000,0.933673,1
2,Random Forest,0.759204,0.969119,0.942380,1.000000,0.917676,2
1,Decision Tree,0.659834,0.822013,0.933781,1.000000,0.853907,3
4,MLP,0.602276,0.717234,0.935524,1.000000,0.813759,4
3,XGBoost,0.671273,0.000000,0.942408,1.000000,0.653420,5

====================================================================================================
REPETITION 3/20 | seed=44
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  4.85it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  1.74it/s]
100%|██████████| 1/1 [00:00<00:00,  5.13it/s]
100%|██████████| 1/1 [00:00<00:00,  1.26it/s]
100%|██████████| 1/1 [00:00<00:00,  4.20it/s]
100%|██████████| 1/1 [00:00<00:00,  2.05it/s]
100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
100%|██████████| 1/1 [00:01<00:00,  1.80s/it]
100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
100%|██████████| 1/1 [00:01<00:00,  1.39s/it]
100%|██████████| 1/1 [00:00<00:00,  6.14it/s]
100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
100%|██████████| 1/1 [00:00<00:00,  4.83it/s]
100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
100%|██████████| 1/1 [00:00<00:00,  7.24it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  2.35it/s]
100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
100%|██████████| 1/1 [00:00<00:00,  6.09it/s]
100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
100%|██████████| 1/1 [00:00<00:00,  7.23it/s]
100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
100%|██████████| 1/1 [00:00<00:00,  7.65it/s]
100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
100%|██████████| 1/1 [00:00<00:00,  1.61it/s]
100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
100%|██████████| 1/1 [00:00<00:00,  7.22it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  2.76it/s]
100%|██████████| 1/1 [00:00<00:00,  2.67it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.66it/s]
100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.69it/s]
100%|██████████| 1/1 [00:00<00:00,  2.28it/s]
100%|██████████| 1/1 [00:00<00:00,  2.76it/s]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.77it/s]
100%|██████████| 1/1 [00:00<00:00,  2.58it/s]
100%|██████████| 1/1 [00:00<00:00,  2.29it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.69it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.75it/s]
100%|██████████| 1/1 [00:00<00:00,  2.74it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.75it/s]
100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.77it/s]
100%|██████████| 1/1 [00:00<00:00,  1.88it/s]
100%|██████████| 1/1 [00:00<00:00,  1.85it/s]
100%|██████████| 1/1 [00:00<00:00,  1.86it/s]
100%|██████████| 1/1 [00:00<00:00,  1.84it/s]
100%|██████████| 1/1 [00:00<00:00,  1.80it/s]
100%|██████████| 1/1 [00:00<00:00,  1.86it/s]
100%|██████████| 1/1 [00:01<00:00,  1.49s/it]
100%|██████████| 1/1 [00:00<00:00,  2.77it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
100%|██████████| 1/1 [00:00<00:00,  2.06it/s]
100%|██████████| 1/1 [00:00<00:00,  3.06it/s]
100%|██████████| 1/1 [00:00<00:00,  5.51it/s]
100%|██████████| 1/1 [00:00<00:00,  6.20it/s]
100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  6.23it/s]
100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
100%|██████████| 1/1 [00:00<00:00,  4.33it/s]
100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
100%|██████████| 1/1 [00:00<00:00,  6.31it/s]
100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
100%|██████████| 1/1 [00:00<00:00,  6.27it/s]
100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
100%|██████████| 1/1 [00:00<00:00,  6.21it/s]
100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.51it/s]
100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
100%|██████████| 1/1 [00:00<00:00,  5.73it/s]
100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
100%|██████████| 1/1 [00:00<00:00,  2.97it/s]
100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
100%|██████████| 1/1 [00:00<00:00,  2.40it/s]
100%|██████████| 1/1 [00:00<00:00,  6.26it/s]
100%|██████████| 1/1 [00:00<00:00,  6.33it/s]
100%|██████████| 1/1 [00:00<00:00,  5.96it/s]
100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  4.01it/s]
100%|██████████| 1/1 [00:00<00:00,  3.19it/s]
100%|██████████| 1/1 [00:00<00:00,  3.15it/s]
100%|██████████| 1/1 [00:00<00:00,  3.21it/s]
100%|██████████| 1/1 [00:00<00:00,  3.85it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  5.89it/s]
100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
100%|██████████| 1/1 [00:00<00:00,  5.70it/s]
100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  4.55it/s]
100%|██████████| 1/1 [00:00<00:00,  5.91it/s]
100%|██████████| 1/1 [00:00<00:00,  5.72it/s]
100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
100%|██████████| 1/1 [00:00<00:00,  1.93it/s]
100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
100%|██████████| 1/1 [00:00<00:00,  5.87it/s]
100%|██████████| 1/1 [00:00<00:00,  4.96it/s]
100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.79it/s]
100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.05it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  5.50it/s]
100%|██████████| 1/1 [00:00<00:00,  2.79it/s]
100%|██████████| 1/1 [00:00<00:00,  5.87it/s]
100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
100%|██████████| 1/1 [00:00<00:00,  5.02it/s]
100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
100%|██████████| 1/1 [00:00<00:00,  5.09it/s]
100%|██████████| 1/1 [00:00<00:00,  4.19it/s]
100%|██████████| 1/1 [00:00<00:00,  3.95it/s]
100%|██████████| 1/1 [00:00<00:00,  2.99it/s]
100%|██████████| 1/1 [00:00<00:00,  3.65it/s]
100%|██████████| 1/1 [00:00<00:00,  3.39it/s]
100%|██████████| 1/1 [00:00<00:00,  2.99it/s]
100%|██████████| 1/1 [00:00<00:00,  3.64it/s]
100%|██████████| 1/1 [00:00<00:00,  3.12it/s]
100%|██████████| 1/1 [00:00<00:00,  3.05it/s]
100%|██████████| 1/1 [00:00<00:00,  3.98it/s]
100%|██████████| 1/1 [00:00<00:00,  3.02it/s]
100%|██████████| 1/1 [00:00<00:00,  3.68it/s]
100%|██████████| 1/1 [00:00<00:00,  2.97it/s]
100%|██████████| 1/1 [00:00<00:00,  4.02it/s]
100%|██████████| 1/1 [00:00<00:00,  3.54it/s]
100%|██████████| 1/1 [00:00<00:00,  3.40it/s]
100%|██████████| 1/1 [00:00<00:00,  3.85it/s]
100%|██████████| 1/1 [00:00<00:00,  4.00it/s]
100%|██████████| 1/1 [00:00<00:00,  2.90it/s]
100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
100%|██████████| 1/1 [00:00<00:00,  5.65it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.783202,0.995566,0.934649,1.000000,0.928354,1
2,Random Forest,0.738804,0.954472,0.935547,1.000000,0.907206,2
1,Decision Tree,0.679929,1.000000,0.942789,1.000000,0.905679,3
4,MLP,0.586745,0.708401,0.943125,1.000000,0.809568,4
3,XGBoost,0.680986,0.000000,0.945109,1.000000,0.656524,5

====================================================================================================
REPETITION 4/20 | seed=45
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
100%|██████████| 1/1 [00:00<00:00,  4.11it/s]
100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.54it/s]
100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
100%|██████████| 1/1 [00:00<00:00,  7.50it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
100%|██████████| 1/1 [00:00<00:00,  1.66it/s]
100%|██████████| 1/1 [00:00<00:00,  4.75it/s]
100%|██████████| 1/1 [00:00<00:00,  3.22it/s]
100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
100%|██████████| 1/1 [00:00<00:00,  1.95it/s]
100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
100%|██████████| 1/1 [00:00<00:00,  1.18it/s]
100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
100%|██████████| 1/1 [00:00<00:00,  4.18it/s]
100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
100%|██████████| 1/1 [00:00<00:00,  2.36it/s]
100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
100%|██████████| 1/1 [00:00<00:00,  3.66it/s]
100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
100%|██████████| 1/1 [00:00<00:00,  4.87it/s]
100%|██████████| 1/1 [00:00<00:00,  4.99it/s]
100%|██████████| 1/1 [00:00<00:00,  4.96it/s]
100%|██████████| 1/1 [00:00<00:00,  5.04it/s]
100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
100%|██████████| 1/1 [00:00<00:00,  5.25it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  2.74it/s]
100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.66it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.77it/s]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.71it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.78it/s]
100%|██████████| 1/1 [00:00<00:00,  2.57it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.23it/s]
100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.75it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:05<00:00,  6.00s/it]
100%|██████████| 1/1 [00:01<00:00,  1.74s/it]
100%|██████████| 1/1 [00:00<00:00,  2.74it/s]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.68it/s]
100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.67it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.78it/s]
100%|██████████| 1/1 [00:00<00:00,  2.57it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.69it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
100%|██████████| 1/1 [00:00<00:00,  6.06it/s]
100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
100%|██████████| 1/1 [00:00<00:00,  5.70it/s]
100%|██████████| 1/1 [00:00<00:00,  6.04it/s]
100%|██████████| 1/1 [00:00<00:00,  1.89it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.91it/s]
100%|██████████| 1/1 [00:00<00:00,  6.31it/s]
100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
100%|██████████| 1/1 [00:00<00:00,  4.88it/s]
100%|██████████| 1/1 [00:00<00:00,  2.82it/s]
100%|██████████| 1/1 [00:00<00:00,  3.10it/s]
100%|██████████| 1/1 [00:00<00:00,  3.23it/s]
100%|██████████| 1/1 [00:00<00:00,  3.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.79it/s]
100%|██████████| 1/1 [00:00<00:00,  2.83it/s]
100%|██████████| 1/1 [00:00<00:00,  2.87it/s]
100%|██████████| 1/1 [00:00<00:00,  2.86it/s]
100%|██████████| 1/1 [00:00<00:00,  3.06it/s]
100%|██████████| 1/1 [00:00<00:00,  2.82it/s]
100%|██████████| 1/1 [00:00<00:00,  2.80it/s]
100%|██████████| 1/1 [00:00<00:00,  3.04it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
100%|██████████| 1/1 [00:00<00:00,  6.22it/s]
100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
100%|██████████| 1/1 [00:00<00:00,  6.26it/s]
100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
100%|██████████| 1/1 [00:00<00:00,  3.40it/s]
100%|██████████| 1/1 [00:00<00:00,  6.27it/s]
100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
100%|██████████| 1/1 [00:00<00:00,  6.02it/s]
100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
100%|██████████| 1/1 [00:00<00:00,  5.98it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
100%|██████████| 1/1 [00:00<00:00,  5.60it/s]
100%|██████████| 1/1 [00:00<00:00,  5.76it/s]
100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
100%|██████████| 1/1 [00:00<00:00,  4.61it/s]
100%|██████████| 1/1 [00:00<00:00,  5.89it/s]
100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
100%|██████████| 1/1 [00:00<00:00,  5.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.00it/s]
100%|██████████| 1/1 [00:00<00:00,  4.87it/s]
100%|██████████| 1/1 [00:00<00:00,  3.83it/s]
100%|██████████| 1/1 [00:00<00:00,  3.25it/s]
100%|██████████| 1/1 [00:00<00:00,  2.90it/s]
100%|██████████| 1/1 [00:00<00:00,  3.09it/s]
100%|██████████| 1/1 [00:00<00:00,  1.26it/s]
100%|██████████| 1/1 [00:00<00:00,  3.06it/s]
100%|██████████| 1/1 [00:00<00:00,  1.38it/s]
100%|██████████| 1/1 [00:00<00:00,  1.56it/s]
100%|██████████| 1/1 [00:00<00:00,  3.86it/s]
100%|██████████| 1/1 [00:00<00:00,  3.04it/s]
100%|██████████| 1/1 [00:00<00:00,  3.81it/s]
100%|██████████| 1/1 [00:00<00:00,  4.46it/s]
100%|██████████| 1/1 [00:00<00:00,  3.56it/s]
100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
100%|██████████| 1/1 [00:00<00:00,  5.54it/s]
100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
100%|██████████| 1/1 [00:00<00:00,  5.26it/s]
100%|██████████| 1/1 [00:00<00:00,  4.91it/s]
100%|██████████| 1/1 [00:00<00:00,  5.56it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  5.56it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  5.57it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
100%|██████████| 1/1 [00:00<00:00,  6.06it/s]
100%|██████████| 1/1 [00:00<00:00,  2.88it/s]
100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
100%|██████████| 1/1 [00:00<00:00,  5.07it/s]
100%|██████████| 1/1 [00:00<00:00,  4.98it/s]
100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
100%|██████████| 1/1 [00:00<00:00,  5.00it/s]
100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.72it/s]
100%|██████████| 1/1 [00:00<00:00,  5.65it/s]
100%|██████████| 1/1 [00:00<00:00,  5.72it/s]
100%|██████████| 1/1 [00:00<00:00,  4.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.61it/s]
100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
100%|██████████| 1/1 [00:01<00:00,  1.59s/it]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  5.46it/s]
100%|██████████| 1/1 [00:00<00:00,  5.54it/s]
100%|██████████| 1/1 [00:00<00:00,  3.51it/s]
100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
100%|██████████| 1/1 [00:00<00:00,  3.47it/s]
100%|██████████| 1/1 [00:00<00:00,  3.87it/s]
100%|██████████| 1/1 [00:00<00:00,  3.10it/s]
100%|██████████| 1/1 [00:00<00:00,  3.95it/s]
100%|██████████| 1/1 [00:00<00:00,  3.19it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.783782,1.000000,0.931357,1.000000,0.928785,1
2,Random Forest,0.728185,0.959013,0.942541,1.000000,0.907435,2
1,Decision Tree,0.690132,0.975533,0.936742,1.000000,0.900602,3
4,MLP,0.573598,0.615367,0.941209,1.000000,0.782543,4
3,XGBoost,0.665203,0.000000,0.942333,1.000000,0.651884,5

====================================================================================================
REPETITION 5/20 | seed=46
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]
100%|██████████| 1/1 [00:00<00:00,  4.38it/s]
100%|██████████| 1/1 [00:02<00:00,  2.20s/it]
100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
100%|██████████| 1/1 [00:00<00:00,  3.31it/s]
100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
100%|██████████| 1/1 [00:00<00:00,  6.83it/s]
100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
100%|██████████| 1/1 [00:00<00:00,  3.01it/s]
100%|██████████| 1/1 [00:00<00:00,  1.94it/s]
100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
100%|██████████| 1/1 [00:00<00:00,  4.28it/s]
100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
100%|██████████| 1/1 [00:00<00:00,  3.12it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  7.23it/s]
100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
100%|██████████| 1/1 [00:00<00:00,  7.00it/s]
100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
100%|██████████| 1/1 [00:00<00:00,  6.46it/s]
100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  7.46it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  1.85it/s]
100%|██████████| 1/1 [00:00<00:00,  1.84it/s]
100%|██████████| 1/1 [00:00<00:00,  1.85it/s]
100%|██████████| 1/1 [00:00<00:00,  1.90it/s]
100%|██████████| 1/1 [00:00<00:00,  1.72it/s]
100%|██████████| 1/1 [00:00<00:00,  1.77it/s]
100%|██████████| 1/1 [00:00<00:00,  1.66it/s]
100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.75it/s]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.74it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.77it/s]
100%|██████████| 1/1 [00:00<00:00,  2.69it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.75it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:00<00:00,  2.42it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.81it/s]
100%|██████████| 1/1 [00:02<00:00,  2.37s/it]
100%|██████████| 1/1 [00:01<00:00,  1.64s/it]
100%|██████████| 1/1 [00:00<00:00,  1.77it/s]
100%|██████████| 1/1 [00:00<00:00,  1.83it/s]
100%|██████████| 1/1 [00:00<00:00,  1.81it/s]
100%|██████████| 1/1 [00:00<00:00,  1.50it/s]
100%|██████████| 1/1 [00:00<00:00,  1.67it/s]
100%|██████████| 1/1 [00:00<00:00,  2.74it/s]
100%|██████████| 1/1 [00:00<00:00,  2.71it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  6.51it/s]
100%|██████████| 1/1 [00:00<00:00,  6.20it/s]
100%|██████████| 1/1 [00:00<00:00,  6.23it/s]
100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  6.27it/s]
100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
100%|██████████| 1/1 [00:00<00:00,  6.35it/s]
100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
100%|██████████| 1/1 [00:00<00:00,  5.89it/s]
100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
100%|██████████| 1/1 [00:00<00:00,  3.96it/s]
100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
100%|██████████| 1/1 [00:00<00:00,  6.10it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  6.35it/s]
100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  6.07it/s]
100%|██████████| 1/1 [00:00<00:00,  6.21it/s]
100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
100%|██████████| 1/1 [00:00<00:00,  3.42it/s]
100%|██████████| 1/1 [00:00<00:00,  3.83it/s]
100%|██████████| 1/1 [00:00<00:00,  4.14it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  5.97it/s]
100%|██████████| 1/1 [00:00<00:00,  5.56it/s]
100%|██████████| 1/1 [00:00<00:00,  5.22it/s]
100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.91it/s]
100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
100%|██████████| 1/1 [00:00<00:00,  5.72it/s]
100%|██████████| 1/1 [00:00<00:00,  5.15it/s]
100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  5.76it/s]
100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.26it/s]
100%|██████████| 1/1 [00:00<00:00,  5.60it/s]
100%|██████████| 1/1 [00:00<00:00,  4.34it/s]
100%|██████████| 1/1 [00:00<00:00,  2.45it/s]
100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
100%|██████████| 1/1 [00:00<00:00,  5.50it/s]
100%|██████████| 1/1 [00:00<00:00,  5.82it/s]
100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.04it/s]
100%|██████████| 1/1 [00:00<00:00,  5.99it/s]
100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.89it/s]
100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
100%|██████████| 1/1 [00:00<00:00,  4.94it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  5.76it/s]
100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.50it/s]
100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
100%|██████████| 1/1 [00:00<00:00,  5.57it/s]
100%|██████████| 1/1 [00:00<00:00,  5.49it/s]
100%|██████████| 1/1 [00:00<00:00,  3.28it/s]
100%|██████████| 1/1 [00:00<00:00,  4.06it/s]
100%|██████████| 1/1 [00:00<00:00,  4.17it/s]
100%|██████████| 1/1 [00:00<00:00,  2.99it/s]
100%|██████████| 1/1 [00:00<00:00,  2.98it/s]
100%|██████████| 1/1 [00:00<00:00,  3.38it/s]
100%|██████████| 1/1 [00:00<00:00,  3.96it/s]
100%|██████████| 1/1 [00:00<00:00,  3.43it/s]
100%|██████████| 1/1 [00:00<00:00,  2.98it/s]
100%|██████████| 1/1 [00:00<00:00,  3.62it/s]
100%|██████████| 1/1 [00:00<00:00,  1.58it/s]
100%|██████████| 1/1 [00:00<00:00,  3.83it/s]
100%|██████████| 1/1 [00:00<00:00,  2.90it/s]
100%|██████████| 1/1 [00:00<00:00,  2.81it/s]
100%|██████████| 1/1 [00:00<00:00,  2.99it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.800235,1.000000,0.944268,1.000000,0.936126,1
2,Random Forest,0.758840,0.953861,0.943888,1.000000,0.914147,2
1,Decision Tree,0.682820,0.994795,0.953295,1.000000,0.907727,3
4,MLP,0.569623,0.648013,0.944577,1.000000,0.790553,4
3,XGBoost,0.672908,0.000000,0.952004,1.000000,0.656228,5

====================================================================================================
REPETITION 6/20 | seed=47
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
100%|██████████| 1/1 [00:00<00:00,  7.16it/s]
100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
100%|██████████| 1/1 [00:00<00:00,  1.02it/s]
100%|██████████| 1/1 [00:00<00:00,  1.37it/s]
100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
100%|██████████| 1/1 [00:00<00:00,  7.49it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
100%|██████████| 1/1 [00:01<00:00,  1.35s/it]
100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
100%|██████████| 1/1 [00:00<00:00,  6.04it/s]
100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
100%|██████████| 1/1 [00:00<00:00,  2.67it/s]
100%|██████████| 1/1 [00:00<00:00,  4.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.05it/s]
100%|██████████| 1/1 [00:00<00:00,  4.96it/s]
100%|██████████| 1/1 [00:00<00:00,  5.01it/s]
100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
100%|██████████| 1/1 [00:00<00:00,  5.07it/s]
100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
100%|██████████| 1/1 [00:00<00:00,  4.99it/s]
100%|██████████| 1/1 [00:02<00:00,  2.46s/it]
100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.37it/s]
100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
100%|██████████| 1/1 [00:00<00:00,  7.45it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.74it/s]
100%|██████████| 1/1 [00:00<00:00,  2.44it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
100%|██████████| 1/1 [00:00<00:00,  2.78it/s]
100%|██████████| 1/1 [00:02<00:00,  2.30s/it]
100%|██████████| 1/1 [00:00<00:00,  1.75it/s]
100%|██████████| 1/1 [00:00<00:00,  1.89it/s]
100%|██████████| 1/1 [00:00<00:00,  1.78it/s]
100%|██████████| 1/1 [00:00<00:00,  1.79it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.78it/s]
100%|██████████| 1/1 [00:01<00:00,  1.41s/it]
100%|██████████| 1/1 [00:00<00:00,  2.47it/s]
100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.68it/s]
100%|██████████| 1/1 [00:00<00:00,  2.58it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
100%|██████████| 1/1 [00:00<00:00,  2.75it/s]
100%|██████████| 1/1 [00:00<00:00,  2.77it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.68it/s]
100%|██████████| 1/1 [00:00<00:00,  2.71it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.67it/s]
100%|██████████| 1/1 [00:00<00:00,  2.74it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  3.06it/s]
100%|██████████| 1/1 [00:00<00:00,  2.96it/s]
100%|██████████| 1/1 [00:00<00:00,  3.38it/s]
100%|██████████| 1/1 [00:00<00:00,  2.87it/s]
100%|██████████| 1/1 [00:00<00:00,  2.89it/s]
100%|██████████| 1/1 [00:00<00:00,  1.75it/s]
100%|██████████| 1/1 [00:00<00:00,  3.08it/s]
100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
100%|██████████| 1/1 [00:00<00:00,  6.17it/s]
100%|██████████| 1/1 [00:00<00:00,  6.27it/s]
100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
100%|██████████| 1/1 [00:00<00:00,  5.45it/s]
100%|██████████| 1/1 [00:00<00:00,  6.46it/s]
100%|██████████| 1/1 [00:00<00:00,  6.17it/s]
100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
100%|██████████| 1/1 [00:00<00:00,  5.61it/s]
100%|██████████| 1/1 [00:00<00:00,  6.20it/s]
100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
100%|██████████| 1/1 [00:00<00:00,  5.46it/s]
100%|██████████| 1/1 [00:00<00:00,  3.50it/s]
100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
100%|██████████| 1/1 [00:00<00:00,  6.07it/s]
100%|██████████| 1/1 [00:00<00:00,  5.26it/s]
100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
100%|██████████| 1/1 [00:00<00:00,  6.06it/s]
100%|██████████| 1/1 [00:00<00:00,  6.22it/s]
100%|██████████| 1/1 [00:00<00:00,  6.14it/s]
100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
100%|██████████| 1/1 [00:00<00:00,  6.36it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  3.36it/s]
100%|██████████| 1/1 [00:00<00:00,  3.07it/s]
100%|██████████| 1/1 [00:00<00:00,  3.20it/s]
100%|██████████| 1/1 [00:00<00:00,  3.06it/s]
100%|██████████| 1/1 [00:00<00:00,  4.00it/s]
100%|██████████| 1/1 [00:00<00:00,  1.55it/s]
100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
100%|██████████| 1/1 [00:00<00:00,  5.46it/s]
100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
100%|██████████| 1/1 [00:00<00:00,  5.54it/s]
100%|██████████| 1/1 [00:00<00:00,  5.72it/s]
100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.27it/s]
100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.49it/s]
100%|██████████| 1/1 [00:00<00:00,  5.82it/s]
100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.01it/s]
100%|██████████| 1/1 [00:00<00:00,  1.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
100%|██████████| 1/1 [00:00<00:00,  4.93it/s]
100%|██████████| 1/1 [00:00<00:00,  1.62it/s]
100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
100%|██████████| 1/1 [00:00<00:00,  5.70it/s]
100%|██████████| 1/1 [00:00<00:00,  5.22it/s]
100%|██████████| 1/1 [00:00<00:00,  5.65it/s]
100%|██████████| 1/1 [00:00<00:00,  5.50it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
100%|██████████| 1/1 [00:00<00:00,  5.54it/s]
100%|██████████| 1/1 [00:00<00:00,  5.06it/s]
100%|██████████| 1/1 [00:00<00:00,  5.56it/s]
100%|██████████| 1/1 [00:00<00:00,  5.50it/s]
100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
100%|██████████| 1/1 [00:01<00:00,  1.79s/it]
100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
100%|██████████| 1/1 [00:00<00:00,  4.99it/s]
100%|██████████| 1/1 [00:00<00:00,  3.28it/s]
100%|██████████| 1/1 [00:00<00:00,  5.00it/s]
100%|██████████| 1/1 [00:00<00:00,  3.13it/s]
100%|██████████| 1/1 [00:00<00:00,  3.11it/s]
100%|██████████| 1/1 [00:00<00:00,  2.98it/s]
100%|██████████| 1/1 [00:00<00:00,  3.12it/s]
100%|██████████| 1/1 [00:00<00:00,  2.95it/s]
100%|██████████| 1/1 [00:00<00:00,  3.52it/s]
100%|██████████| 1/1 [00:00<00:00,  3.05it/s]
100%|██████████| 1/1 [00:00<00:00,  3.42it/s]
100%|██████████| 1/1 [00:00<00:00,  3.12it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.816605,1.000000,0.938231,1.000000,0.938709,1
2,Random Forest,0.783967,0.962219,0.944459,1.000000,0.922661,2
1,Decision Tree,0.728186,0.935479,0.936978,1.000000,0.900161,3
4,MLP,0.585703,0.664862,0.938273,1.000000,0.797209,4
3,XGBoost,0.727901,0.000000,0.949055,1.000000,0.669239,5

====================================================================================================
REPETITION 7/20 | seed=48
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  1.75it/s]
100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
100%|██████████| 1/1 [00:00<00:00,  7.23it/s]
100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
100%|██████████| 1/1 [00:00<00:00,  2.15it/s]
100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
100%|██████████| 1/1 [00:00<00:00,  2.58it/s]
100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
100%|██████████| 1/1 [00:00<00:00,  7.16it/s]
100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
100%|██████████| 1/1 [00:00<00:00,  7.16it/s]
100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
100%|██████████| 1/1 [00:00<00:00,  6.67it/s]
100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
100%|██████████| 1/1 [00:00<00:00,  7.23it/s]
100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
100%|██████████| 1/1 [00:00<00:00,  2.04it/s]
100%|██████████| 1/1 [00:00<00:00,  6.39it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
100%|██████████| 1/1 [00:00<00:00,  2.78it/s]
100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
100%|██████████| 1/1 [00:00<00:00,  3.03it/s]
100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
100%|██████████| 1/1 [00:00<00:00,  6.83it/s]
100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
100%|██████████| 1/1 [00:00<00:00,  5.92it/s]
100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
100%|██████████| 1/1 [00:00<00:00,  6.64it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  1.76it/s]
100%|██████████| 1/1 [00:00<00:00,  1.68it/s]
100%|██████████| 1/1 [00:00<00:00,  2.66it/s]
100%|██████████| 1/1 [00:06<00:00,  6.29s/it]
100%|██████████| 1/1 [00:00<00:00,  1.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.75it/s]
100%|██████████| 1/1 [00:00<00:00,  2.68it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  1.88it/s]
100%|██████████| 1/1 [00:00<00:00,  2.76it/s]
100%|██████████| 1/1 [00:00<00:00,  2.13it/s]
100%|██████████| 1/1 [00:00<00:00,  1.73it/s]
100%|██████████| 1/1 [00:00<00:00,  1.71it/s]
100%|██████████| 1/1 [00:00<00:00,  1.72it/s]
100%|██████████| 1/1 [00:00<00:00,  1.82it/s]
100%|██████████| 1/1 [00:00<00:00,  1.84it/s]
100%|██████████| 1/1 [00:00<00:00,  1.74it/s]
100%|██████████| 1/1 [00:00<00:00,  1.69it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
100%|██████████| 1/1 [00:00<00:00,  2.67it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.66it/s]
100%|██████████| 1/1 [00:00<00:00,  2.58it/s]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.57it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.71it/s]
100%|██████████| 1/1 [00:00<00:00,  2.75it/s]
100%|██████████| 1/1 [00:00<00:00,  2.58it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
100%|██████████| 1/1 [00:01<00:00,  1.33s/it]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  2.03it/s]
100%|██████████| 1/1 [00:02<00:00,  2.06s/it]
100%|██████████| 1/1 [00:00<00:00,  6.10it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
100%|██████████| 1/1 [00:00<00:00,  5.97it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  6.20it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  5.51it/s]
100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  5.99it/s]
100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
100%|██████████| 1/1 [00:00<00:00,  3.95it/s]
100%|██████████| 1/1 [00:00<00:00,  4.90it/s]
100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
100%|██████████| 1/1 [00:00<00:00,  5.72it/s]
100%|██████████| 1/1 [00:00<00:00,  5.52it/s]
100%|██████████| 1/1 [00:00<00:00,  1.18it/s]
100%|██████████| 1/1 [00:00<00:00,  5.18it/s]
100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
100%|██████████| 1/1 [00:00<00:00,  6.02it/s]
100%|██████████| 1/1 [00:00<00:00,  1.68it/s]
100%|██████████| 1/1 [00:00<00:00,  5.73it/s]
100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
100%|██████████| 1/1 [00:00<00:00,  3.79it/s]
100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
100%|██████████| 1/1 [00:00<00:00,  5.99it/s]
100%|██████████| 1/1 [00:00<00:00,  5.70it/s]
100%|██████████| 1/1 [00:00<00:00,  5.21it/s]
100%|██████████| 1/1 [00:01<00:00,  1.13s/it]
100%|██████████| 1/1 [00:00<00:00,  3.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.75it/s]
100%|██████████| 1/1 [00:00<00:00,  3.47it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.83it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  5.72it/s]
100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
100%|██████████| 1/1 [00:00<00:00,  1.72it/s]
100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
100%|██████████| 1/1 [00:00<00:00,  5.70it/s]
100%|██████████| 1/1 [00:00<00:00,  4.85it/s]
100%|██████████| 1/1 [00:00<00:00,  5.79it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  3.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.82it/s]
100%|██████████| 1/1 [00:00<00:00,  4.69it/s]
100%|██████████| 1/1 [00:00<00:00,  5.56it/s]
100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
100%|██████████| 1/1 [00:00<00:00,  4.56it/s]
100%|██████████| 1/1 [00:00<00:00,  3.45it/s]
100%|██████████| 1/1 [00:00<00:00,  3.81it/s]
100%|██████████| 1/1 [00:00<00:00,  3.03it/s]
100%|██████████| 1/1 [00:00<00:00,  3.04it/s]
100%|██████████| 1/1 [00:00<00:00,  3.35it/s]
100%|██████████| 1/1 [00:00<00:00,  3.01it/s]
100%|██████████| 1/1 [00:00<00:00,  3.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.91it/s]
100%|██████████| 1/1 [00:00<00:00,  3.08it/s]
100%|██████████| 1/1 [00:00<00:00,  3.11it/s]
100%|██████████| 1/1 [00:00<00:00,  3.10it/s]
100%|██████████| 1/1 [00:00<00:00,  3.10it/s]
100%|██████████| 1/1 [00:00<00:00,  2.87it/s]
100%|██████████| 1/1 [00:00<00:00,  3.02it/s]
100%|██████████| 1/1 [00:00<00:00,  4.25it/s]
100%|██████████| 1/1 [00:00<00:00,  4.28it/s]
100%|██████████| 1/1 [00:00<00:00,  3.37it/s]
100%|██████████| 1/1 [00:00<00:00,  4.64it/s]
100%|██████████| 1/1 [00:00<00:00,  5.54it/s]
100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
100%|██████████| 1/1 [00:00<00:00,  5.50it/s]
100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  4.91it/s]
100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.50it/s]
100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
100%|██████████| 1/1 [00:00<00:00,  4.58it/s]
100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  4.51it/s]
100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
100%|██████████| 1/1 [00:00<00:00,  2.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.51it/s]
100%|██████████| 1/1 [00:00<00:00,  5.07it/s]
100%|██████████| 1/1 [00:00<00:00,  5.50it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.54it/s]
100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
100%|██████████| 1/1 [00:00<00:00,  4.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.45it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.97it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  4.65it/s]
100%|██████████| 1/1 [00:00<00:00,  5.72it/s]
100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
100%|██████████| 1/1 [00:00<00:00,  5.65it/s]
100%|██████████| 1/1 [00:00<00:00,  3.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.00it/s]
100%|██████████| 1/1 [00:00<00:00,  5.61it/s]
100%|██████████| 1/1 [00:00<00:00,  5.54it/s]
100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
100%|██████████| 1/1 [00:00<00:00,  5.05it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.816948,1.000000,0.931695,1.000000,0.937161,1
2,Random Forest,0.766982,0.967985,0.936592,1.000000,0.917890,2
1,Decision Tree,0.672934,0.989241,0.932561,1.000000,0.898684,3
4,MLP,0.555479,0.642389,0.937723,1.000000,0.783898,4
3,XGBoost,0.706071,0.000000,0.938816,1.000000,0.661222,5

====================================================================================================
REPETITION 8/20 | seed=49
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
100%|██████████| 1/1 [00:00<00:00,  4.60it/s]
100%|██████████| 1/1 [00:00<00:00,  4.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.20it/s]
100%|██████████| 1/1 [00:00<00:00,  5.12it/s]
100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
100%|██████████| 1/1 [00:00<00:00,  4.97it/s]
100%|██████████| 1/1 [00:00<00:00,  4.61it/s]
100%|██████████| 1/1 [00:00<00:00,  4.75it/s]
100%|██████████| 1/1 [00:00<00:00,  4.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.32it/s]
100%|██████████| 1/1 [00:00<00:00,  4.29it/s]
100%|██████████| 1/1 [00:00<00:00,  5.02it/s]
100%|██████████| 1/1 [00:00<00:00,  4.85it/s]
100%|██████████| 1/1 [00:00<00:00,  4.96it/s]
100%|██████████| 1/1 [00:00<00:00,  5.07it/s]
100%|██████████| 1/1 [00:00<00:00,  1.84it/s]
100%|██████████| 1/1 [00:00<00:00,  4.62it/s]
100%|██████████| 1/1 [00:00<00:00,  4.93it/s]
100%|██████████| 1/1 [00:00<00:00,  6.23it/s]
100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
100%|██████████| 1/1 [00:00<00:00,  4.75it/s]
100%|██████████| 1/1 [00:00<00:00,  6.33it/s]
100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
100%|██████████| 1/1 [00:00<00:00,  7.00it/s]
100%|██████████| 1/1 [00:00<00:00,  5.43it/s]
100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
100%|██████████| 1/1 [00:00<00:00,  6.98it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  4.86it/s]
100%|██████████| 1/1 [00:00<00:00,  1.63it/s]
100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
100%|██████████| 1/1 [00:00<00:00,  4.44it/s]
100%|██████████| 1/1 [00:00<00:00,  4.86it/s]
100%|██████████| 1/1 [00:00<00:00,  4.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  4.72it/s]
100%|██████████| 1/1 [00:00<00:00,  4.13it/s]
100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
100%|██████████| 1/1 [00:00<00:00,  2.94it/s]
100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  7.02it/s]
100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
100%|██████████| 1/1 [00:00<00:00,  7.02it/s]
100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
100%|██████████| 1/1 [00:00<00:00,  7.00it/s]
100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
100%|██████████| 1/1 [00:00<00:00,  2.12it/s]
100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
100%|██████████| 1/1 [00:00<00:00,  2.39it/s]
100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
100%|██████████| 1/1 [00:00<00:00,  3.24it/s]
100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
100%|██████████| 1/1 [00:00<00:00,  6.21it/s]
100%|██████████| 1/1 [00:00<00:00,  7.14it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  1.97it/s]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.66it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.68it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.57it/s]
100%|██████████| 1/1 [00:00<00:00,  2.43it/s]
100%|██████████| 1/1 [00:00<00:00,  2.71it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:00<00:00,  2.67it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.74it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:00<00:00,  2.43it/s]
100%|██████████| 1/1 [00:00<00:00,  1.77it/s]
100%|██████████| 1/1 [00:00<00:00,  1.84it/s]
100%|██████████| 1/1 [00:00<00:00,  1.85it/s]
100%|██████████| 1/1 [00:00<00:00,  1.52it/s]
100%|██████████| 1/1 [00:00<00:00,  1.88it/s]
100%|██████████| 1/1 [00:00<00:00,  1.76it/s]
100%|██████████| 1/1 [00:00<00:00,  1.83it/s]
100%|██████████| 1/1 [00:00<00:00,  1.95it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
100%|██████████| 1/1 [00:00<00:00,  5.35it/s]
100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
100%|██████████| 1/1 [00:00<00:00,  5.95it/s]
100%|██████████| 1/1 [00:00<00:00,  5.91it/s]
100%|██████████| 1/1 [00:00<00:00,  6.10it/s]
100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
100%|██████████| 1/1 [00:00<00:00,  5.43it/s]
100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
100%|██████████| 1/1 [00:00<00:00,  6.27it/s]
100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
100%|██████████| 1/1 [00:00<00:00,  5.98it/s]
100%|██████████| 1/1 [00:00<00:00,  5.41it/s]
100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
100%|██████████| 1/1 [00:00<00:00,  6.06it/s]
100%|██████████| 1/1 [00:00<00:00,  6.02it/s]
100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.96it/s]
100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
100%|██████████| 1/1 [00:00<00:00,  5.98it/s]
100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
100%|██████████| 1/1 [00:00<00:00,  1.52it/s]
100%|██████████| 1/1 [00:00<00:00,  6.20it/s]
100%|██████████| 1/1 [00:00<00:00,  2.38it/s]
100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
100%|██████████| 1/1 [00:00<00:00,  5.95it/s]
100%|██████████| 1/1 [00:00<00:00,  1.13it/s]
100%|██████████| 1/1 [00:00<00:00,  2.83it/s]
100%|██████████| 1/1 [00:00<00:00,  3.78it/s]
100%|██████████| 1/1 [00:00<00:00,  3.02it/s]
100%|██████████| 1/1 [00:00<00:00,  3.56it/s]
100%|██████████| 1/1 [00:00<00:00,  1.27it/s]
100%|██████████| 1/1 [00:00<00:00,  2.68it/s]
100%|██████████| 1/1 [00:00<00:00,  4.21it/s]
100%|██████████| 1/1 [00:00<00:00,  4.36it/s]
100%|██████████| 1/1 [00:00<00:00,  3.04it/s]
100%|██████████| 1/1 [00:00<00:00,  3.55it/s]
100%|██████████| 1/1 [00:00<00:00,  5.98it/s]
100%|██████████| 1/1 [00:00<00:00,  6.09it/s]
100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
100%|██████████| 1/1 [00:00<00:00,  6.20it/s]
100%|██████████| 1/1 [00:00<00:00,  6.23it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.46it/s]
100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
100%|██████████| 1/1 [00:00<00:00,  4.77it/s]
100%|██████████| 1/1 [00:00<00:00,  5.54it/s]
100%|██████████| 1/1 [00:00<00:00,  5.65it/s]
100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
100%|██████████| 1/1 [00:00<00:00,  5.52it/s]
100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
100%|██████████| 1/1 [00:00<00:00,  4.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.43it/s]
100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
100%|██████████| 1/1 [00:00<00:00,  5.52it/s]
100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
100%|██████████| 1/1 [00:00<00:00,  4.86it/s]
100%|██████████| 1/1 [00:00<00:00,  5.35it/s]
100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.39it/s]
100%|██████████| 1/1 [00:00<00:00,  3.23it/s]
100%|██████████| 1/1 [00:00<00:00,  3.91it/s]
100%|██████████| 1/1 [00:00<00:00,  3.05it/s]
100%|██████████| 1/1 [00:00<00:00,  3.03it/s]
100%|██████████| 1/1 [00:00<00:00,  2.88it/s]
100%|██████████| 1/1 [00:00<00:00,  3.25it/s]
100%|██████████| 1/1 [00:00<00:00,  4.09it/s]
100%|██████████| 1/1 [00:00<00:00,  2.96it/s]
100%|██████████| 1/1 [00:00<00:00,  2.91it/s]
100%|██████████| 1/1 [00:00<00:00,  2.95it/s]
100%|██████████| 1/1 [00:00<00:00,  4.53it/s]
100%|██████████| 1/1 [00:00<00:00,  4.28it/s]
100%|██████████| 1/1 [00:00<00:00,  3.64it/s]
100%|██████████| 1/1 [00:00<00:00,  3.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  3.45it/s]
100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
100%|██████████| 1/1 [00:00<00:00,  5.52it/s]
100%|██████████| 1/1 [00:00<00:00,  4.92it/s]
100%|██████████| 1/1 [00:00<00:00,  3.43it/s]
100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.13it/s]
100%|██████████| 1/1 [00:00<00:00,  5.39it/s]
100%|██████████| 1/1 [00:00<00:00,  5.07it/s]
100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.57it/s]
100%|██████████| 1/1 [00:00<00:00,  4.90it/s]
100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.29it/s]
100%|██████████| 1/1 [00:00<00:00,  5.57it/s]
100%|██████████| 1/1 [00:00<00:00,  5.20it/s]
100%|██████████| 1/1 [00:00<00:00,  5.27it/s]
100%|██████████| 1/1 [00:00<00:00,  5.57it/s]
100%|██████████| 1/1 [00:00<00:00,  5.51it/s]
100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
100%|██████████| 1/1 [00:00<00:00,  3.04it/s]
100%|██████████| 1/1 [00:00<00:00,  5.65it/s]
100%|██████████| 1/1 [00:00<00:00,  5.61it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.43it/s]
100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
100%|██████████| 1/1 [00:00<00:00,  4.74it/s]
100%|██████████| 1/1 [00:00<00:00,  5.54it/s]
100%|██████████| 1/1 [00:00<00:00,  5.52it/s]
100%|██████████| 1/1 [00:00<00:00,  5.72it/s]
100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
100%|██████████| 1/1 [00:00<00:00,  5.12it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.768419,1.000000,0.935670,1.000000,0.926022,1
2,Random Forest,0.760103,0.939813,0.939797,1.000000,0.909928,2
1,Decision Tree,0.686961,0.966956,0.946002,1.000000,0.899980,3
4,MLP,0.556499,0.595451,0.939226,1.000000,0.772794,4
3,XGBoost,0.694612,0.000000,0.946174,1.000000,0.660197,5

====================================================================================================
REPETITION 9/20 | seed=50
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
100%|██████████| 1/1 [00:00<00:00,  7.02it/s]
100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
100%|██████████| 1/1 [00:00<00:00,  2.16it/s]
100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
100%|██████████| 1/1 [00:00<00:00,  6.46it/s]
100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
100%|██████████| 1/1 [00:00<00:00,  4.78it/s]
100%|██████████| 1/1 [00:00<00:00,  4.39it/s]
100%|██████████| 1/1 [00:00<00:00,  4.76it/s]
100%|██████████| 1/1 [00:00<00:00,  5.03it/s]
100%|██████████| 1/1 [00:00<00:00,  4.67it/s]
100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
100%|██████████| 1/1 [00:00<00:00,  4.76it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  4.71it/s]
100%|██████████| 1/1 [00:00<00:00,  4.81it/s]
100%|██████████| 1/1 [00:00<00:00,  4.83it/s]
100%|██████████| 1/1 [00:00<00:00,  4.33it/s]
100%|██████████| 1/1 [00:00<00:00,  2.42it/s]
100%|██████████| 1/1 [00:00<00:00,  5.27it/s]
100%|██████████| 1/1 [00:00<00:00,  4.71it/s]
100%|██████████| 1/1 [00:00<00:00,  4.42it/s]
100%|██████████| 1/1 [00:00<00:00,  4.78it/s]
100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
100%|██████████| 1/1 [00:00<00:00,  4.61it/s]
100%|██████████| 1/1 [00:00<00:00,  4.57it/s]
100%|██████████| 1/1 [00:00<00:00,  4.41it/s]
100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
100%|██████████| 1/1 [00:00<00:00,  7.16it/s]
100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.17it/s]
100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
100%|██████████| 1/1 [00:00<00:00,  7.24it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
100%|██████████| 1/1 [00:00<00:00,  1.83it/s]
100%|██████████| 1/1 [00:01<00:00,  1.98s/it]
100%|██████████| 1/1 [00:00<00:00,  5.09it/s]
100%|██████████| 1/1 [00:00<00:00,  5.02it/s]
100%|██████████| 1/1 [00:00<00:00,  4.87it/s]
100%|██████████| 1/1 [00:00<00:00,  5.06it/s]
100%|██████████| 1/1 [00:00<00:00,  4.71it/s]
100%|██████████| 1/1 [00:00<00:00,  4.83it/s]
100%|██████████| 1/1 [00:00<00:00,  4.81it/s]
100%|██████████| 1/1 [00:00<00:00,  4.40it/s]
100%|██████████| 1/1 [00:00<00:00,  4.64it/s]
100%|██████████| 1/1 [00:00<00:00,  3.87it/s]
100%|██████████| 1/1 [00:00<00:00,  4.89it/s]
100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
100%|██████████| 1/1 [00:00<00:00,  6.14it/s]
100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
100%|██████████| 1/1 [00:00<00:00,  3.89it/s]
100%|██████████| 1/1 [00:00<00:00,  7.02it/s]
100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
100%|██████████| 1/1 [00:00<00:00,  6.21it/s]
100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
100%|██████████| 1/1 [00:01<00:00,  1.49s/it]
100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
100%|██████████| 1/1 [00:00<00:00,  6.68it/s]
100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
100%|██████████| 1/1 [00:00<00:00,  1.83it/s]
100%|██████████| 1/1 [00:00<00:00,  1.09it/s]
100%|██████████| 1/1 [00:00<00:00,  7.10it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  2.33it/s]
100%|██████████| 1/1 [00:00<00:00,  2.36it/s]
100%|██████████| 1/1 [00:00<00:00,  2.26it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.71it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.69it/s]
100%|██████████| 1/1 [00:00<00:00,  2.69it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.74it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.74it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  1.75it/s]
100%|██████████| 1/1 [00:00<00:00,  1.79it/s]
100%|██████████| 1/1 [00:00<00:00,  1.77it/s]
100%|██████████| 1/1 [00:00<00:00,  1.69it/s]
100%|██████████| 1/1 [00:00<00:00,  1.82it/s]
100%|██████████| 1/1 [00:00<00:00,  1.73it/s]
100%|██████████| 1/1 [00:00<00:00,  1.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.02it/s]
100%|██████████| 1/1 [00:00<00:00,  2.68it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.40it/s]
100%|██████████| 1/1 [00:00<00:00,  2.68it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.66it/s]
100%|██████████| 1/1 [00:00<00:00,  1.40it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  1.43it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.66it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:00<00:00,  2.58it/s]
100%|██████████| 1/1 [00:00<00:00,  2.22it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  3.98it/s]
100%|██████████| 1/1 [00:00<00:00,  2.89it/s]
100%|██████████| 1/1 [00:00<00:00,  3.06it/s]
100%|██████████| 1/1 [00:00<00:00,  1.94it/s]
100%|██████████| 1/1 [00:00<00:00,  2.79it/s]
100%|██████████| 1/1 [00:01<00:00,  1.28s/it]
100%|██████████| 1/1 [00:00<00:00,  3.45it/s]
100%|██████████| 1/1 [00:00<00:00,  3.36it/s]
100%|██████████| 1/1 [00:00<00:00,  2.94it/s]
100%|██████████| 1/1 [00:00<00:00,  5.95it/s]
100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
100%|██████████| 1/1 [00:00<00:00,  5.95it/s]
100%|██████████| 1/1 [00:00<00:00,  5.52it/s]
100%|██████████| 1/1 [00:00<00:00,  3.10it/s]
100%|██████████| 1/1 [00:00<00:00,  2.31it/s]
100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
100%|██████████| 1/1 [00:00<00:00,  5.76it/s]
100%|██████████| 1/1 [00:00<00:00,  5.89it/s]
100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  5.92it/s]
100%|██████████| 1/1 [00:00<00:00,  6.09it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
100%|██████████| 1/1 [00:00<00:00,  5.06it/s]
100%|██████████| 1/1 [00:00<00:00,  5.94it/s]
100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
100%|██████████| 1/1 [00:00<00:00,  5.57it/s]
100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
100%|██████████| 1/1 [00:00<00:00,  5.01it/s]
100%|██████████| 1/1 [00:00<00:00,  3.46it/s]
100%|██████████| 1/1 [00:00<00:00,  5.73it/s]
100%|██████████| 1/1 [00:01<00:00,  1.91s/it]
100%|██████████| 1/1 [00:00<00:00,  5.89it/s]
100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  6.22it/s]
100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
100%|██████████| 1/1 [00:00<00:00,  5.82it/s]
100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.51it/s]
100%|██████████| 1/1 [00:00<00:00,  6.02it/s]
100%|██████████| 1/1 [00:00<00:00,  5.72it/s]
100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
100%|██████████| 1/1 [00:00<00:00,  3.72it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  5.91it/s]
100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
100%|██████████| 1/1 [00:00<00:00,  5.42it/s]
100%|██████████| 1/1 [00:00<00:00,  4.77it/s]
100%|██████████| 1/1 [00:00<00:00,  5.02it/s]
100%|██████████| 1/1 [00:00<00:00,  2.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
100%|██████████| 1/1 [00:00<00:00,  5.15it/s]
100%|██████████| 1/1 [00:00<00:00,  5.42it/s]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  5.57it/s]
100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
100%|██████████| 1/1 [00:00<00:00,  4.74it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  4.91it/s]
100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
100%|██████████| 1/1 [00:00<00:00,  5.27it/s]
100%|██████████| 1/1 [00:00<00:00,  5.52it/s]
100%|██████████| 1/1 [00:00<00:00,  5.46it/s]
100%|██████████| 1/1 [00:00<00:00,  4.81it/s]
100%|██████████| 1/1 [00:00<00:00,  5.65it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  5.29it/s]
100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
100%|██████████| 1/1 [00:00<00:00,  3.43it/s]
100%|██████████| 1/1 [00:00<00:00,  3.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:00<00:00,  1.25it/s]
100%|██████████| 1/1 [00:00<00:00,  3.76it/s]
100%|██████████| 1/1 [00:00<00:00,  3.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.95it/s]
100%|██████████| 1/1 [00:00<00:00,  1.90it/s]
100%|██████████| 1/1 [00:00<00:00,  4.45it/s]
100%|██████████| 1/1 [00:00<00:00,  3.11it/s]
100%|██████████| 1/1 [00:00<00:00,  2.98it/s]
100%|██████████| 1/1 [00:00<00:00,  2.84it/s]
100%|██████████| 1/1 [00:00<00:00,  2.85it/s]
100%|██████████| 1/1 [00:00<00:00,  5.23it/s]
100%|██████████| 1/1 [00:00<00:00,  5.65it/s]
100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
100%|██████████| 1/1 [00:00<00:00,  5.15it/s]
100%|██████████| 1/1 [00:00<00:00,  5.46it/s]
100%|██████████| 1/1 [00:00<00:00,  5.51it/s]
100%|██████████| 1/1 [00:00<00:00,  5.13it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  3.02it/s]
100%|██████████| 1/1 [00:00<00:00,  5.54it/s]
100%|██████████| 1/1 [00:00<00:00,  5.42it/s]
100%|██████████| 1/1 [00:00<00:00,  5.57it/s]
100%|██████████| 1/1 [00:00<00:00,  5.26it/s]
100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.43it/s]
100%|██████████| 1/1 [00:00<00:00,  4.83it/s]
100%|██████████| 1/1 [00:00<00:00,  1.98it/s]
100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
100%|██████████| 1/1 [00:00<00:00,  4.40it/s]
100%|██████████| 1/1 [00:00<00:00,  5.62it/s]
100%|██████████| 1/1 [00:00<00:00,  5.39it/s]
100%|██████████| 1/1 [00:00<00:00,  5.41it/s]
100%|██████████| 1/1 [00:00<00:00,  5.54it/s]
100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
100%|██████████| 1/1 [00:00<00:00,  5.46it/s]
100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
100%|██████████| 1/1 [00:00<00:00,  3.94it/s]
100%|██████████| 1/1 [00:00<00:00,  5.21it/s]
100%|██████████| 1/1 [00:00<00:00,  5.02it/s]
100%|██████████| 1/1 [00:00<00:00,  5.52it/s]
100%|██████████| 1/1 [00:00<00:00,  5.52it/s]
100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
100%|██████████| 1/1 [00:00<00:00,  4.54it/s]
100%|██████████| 1/1 [00:00<00:00,  5.56it/s]
100%|██████████| 1/1 [00:00<00:00,  5.49it/s]
100%|██████████| 1/1 [00:00<00:00,  5.60it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  4.98it/s]
100%|██████████| 1/1 [00:00<00:00,  5.52it/s]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  5.62it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.764899,0.958215,0.933175,1.000000,0.914072,1
2,Random Forest,0.728908,0.936859,0.935779,1.000000,0.900387,2
1,Decision Tree,0.645581,1.000000,0.925907,1.000000,0.892872,3
4,MLP,0.579826,0.526725,0.936529,1.000000,0.760770,4
3,XGBoost,0.676273,0.000000,0.940707,1.000000,0.654245,5

====================================================================================================
REPETITION 10/20 | seed=51
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
100%|██████████| 1/1 [00:00<00:00,  5.27it/s]
100%|██████████| 1/1 [00:00<00:00,  4.73it/s]
100%|██████████| 1/1 [00:00<00:00,  4.61it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
100%|██████████| 1/1 [00:00<00:00,  4.92it/s]
100%|██████████| 1/1 [00:00<00:00,  4.37it/s]
100%|██████████| 1/1 [00:00<00:00,  4.20it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:00<00:00,  4.90it/s]
100%|██████████| 1/1 [00:00<00:00,  1.68it/s]
100%|██████████| 1/1 [00:00<00:00,  4.56it/s]
100%|██████████| 1/1 [00:00<00:00,  4.85it/s]
100%|██████████| 1/1 [00:00<00:00,  4.50it/s]
100%|██████████| 1/1 [00:00<00:00,  4.28it/s]
100%|██████████| 1/1 [00:00<00:00,  4.85it/s]
100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
100%|██████████| 1/1 [00:00<00:00,  6.23it/s]
100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
100%|██████████| 1/1 [00:00<00:00,  6.33it/s]
100%|██████████| 1/1 [00:00<00:00,  3.23it/s]
100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
100%|██████████| 1/1 [00:00<00:00,  3.43it/s]
100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
100%|██████████| 1/1 [00:00<00:00,  7.02it/s]
100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
100%|██████████| 1/1 [00:01<00:00,  1.26s/it]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
100%|██████████| 1/1 [00:00<00:00,  3.20it/s]
100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
100%|██████████| 1/1 [00:00<00:00,  2.20it/s]
100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
100%|██████████| 1/1 [00:00<00:00,  5.89it/s]
100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
100%|██████████| 1/1 [00:00<00:00,  6.26it/s]
100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
100%|██████████| 1/1 [00:01<00:00,  1.90s/it]
100%|██████████| 1/1 [00:00<00:00,  4.85it/s]
100%|██████████| 1/1 [00:00<00:00,  1.62it/s]
100%|██████████| 1/1 [00:00<00:00,  4.61it/s]
100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
100%|██████████| 1/1 [00:00<00:00,  4.83it/s]
100%|██████████| 1/1 [00:00<00:00,  4.36it/s]
100%|██████████| 1/1 [00:00<00:00,  1.72it/s]
100%|██████████| 1/1 [00:00<00:00,  5.02it/s]
100%|██████████| 1/1 [00:00<00:00,  5.09it/s]
100%|██████████| 1/1 [00:00<00:00,  4.89it/s]
100%|██████████| 1/1 [00:00<00:00,  4.74it/s]
100%|██████████| 1/1 [00:00<00:00,  4.76it/s]
100%|██████████| 1/1 [00:00<00:00,  2.24it/s]
100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  4.77it/s]
100%|██████████| 1/1 [00:00<00:00,  4.15it/s]
100%|██████████| 1/1 [00:00<00:00,  4.44it/s]
100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
100%|██████████| 1/1 [00:00<00:00,  6.31it/s]
100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
100%|██████████| 1/1 [00:00<00:00,  4.75it/s]
100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
100%|██████████| 1/1 [00:00<00:00,  6.94it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  2.44it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  1.05it/s]
100%|██████████| 1/1 [00:00<00:00,  1.74it/s]
100%|██████████| 1/1 [00:00<00:00,  1.89it/s]
100%|██████████| 1/1 [00:00<00:00,  1.71it/s]
100%|██████████| 1/1 [00:00<00:00,  1.76it/s]
100%|██████████| 1/1 [00:00<00:00,  1.75it/s]
100%|██████████| 1/1 [00:00<00:00,  1.69it/s]
100%|██████████| 1/1 [00:00<00:00,  1.66it/s]
100%|██████████| 1/1 [00:00<00:00,  2.26it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.45it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:00<00:00,  2.50it/s]
100%|██████████| 1/1 [00:00<00:00,  2.66it/s]
100%|██████████| 1/1 [00:00<00:00,  2.47it/s]
100%|██████████| 1/1 [00:00<00:00,  2.69it/s]
100%|██████████| 1/1 [00:00<00:00,  2.68it/s]
100%|██████████| 1/1 [00:00<00:00,  2.58it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.67it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.58it/s]
100%|██████████| 1/1 [00:00<00:00,  2.74it/s]
100%|██████████| 1/1 [00:00<00:00,  2.57it/s]
100%|██████████| 1/1 [00:00<00:00,  1.97it/s]
100%|██████████| 1/1 [00:00<00:00,  1.78it/s]
100%|██████████| 1/1 [00:00<00:00,  1.75it/s]
100%|██████████| 1/1 [00:00<00:00,  1.65it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  6.23it/s]
100%|██████████| 1/1 [00:00<00:00,  6.04it/s]
100%|██████████| 1/1 [00:00<00:00,  5.76it/s]
100%|██████████| 1/1 [00:00<00:00,  5.96it/s]
100%|██████████| 1/1 [00:00<00:00,  5.41it/s]
100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
100%|██████████| 1/1 [00:00<00:00,  5.95it/s]
100%|██████████| 1/1 [00:01<00:00,  1.51s/it]
100%|██████████| 1/1 [00:00<00:00,  5.18it/s]
100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
100%|██████████| 1/1 [00:00<00:00,  5.72it/s]
100%|██████████| 1/1 [00:00<00:00,  5.43it/s]
100%|██████████| 1/1 [00:00<00:00,  5.87it/s]
100%|██████████| 1/1 [00:00<00:00,  5.97it/s]
100%|██████████| 1/1 [00:01<00:00,  1.82s/it]
100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
100%|██████████| 1/1 [00:00<00:00,  4.65it/s]
100%|██████████| 1/1 [00:00<00:00,  3.35it/s]
100%|██████████| 1/1 [00:00<00:00,  3.66it/s]
100%|██████████| 1/1 [00:00<00:00,  4.44it/s]
100%|██████████| 1/1 [00:00<00:00,  3.27it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.84it/s]
100%|██████████| 1/1 [00:00<00:00,  3.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.78it/s]
100%|██████████| 1/1 [00:00<00:00,  2.76it/s]
100%|██████████| 1/1 [00:00<00:00,  2.83it/s]
100%|██████████| 1/1 [00:00<00:00,  3.21it/s]
100%|██████████| 1/1 [00:00<00:00,  3.83it/s]
100%|██████████| 1/1 [00:00<00:00,  3.52it/s]
100%|██████████| 1/1 [00:00<00:00,  3.07it/s]
100%|██████████| 1/1 [00:00<00:00,  4.86it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  4.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.61it/s]
100%|██████████| 1/1 [00:00<00:00,  5.21it/s]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  5.46it/s]
100%|██████████| 1/1 [00:00<00:00,  5.39it/s]
100%|██████████| 1/1 [00:00<00:00,  5.12it/s]
100%|██████████| 1/1 [00:00<00:00,  5.18it/s]
100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
100%|██████████| 1/1 [00:00<00:00,  4.73it/s]
100%|██████████| 1/1 [00:00<00:00,  5.22it/s]
100%|██████████| 1/1 [00:00<00:00,  5.43it/s]
100%|██████████| 1/1 [00:00<00:00,  5.35it/s]
100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
100%|██████████| 1/1 [00:00<00:00,  4.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
100%|██████████| 1/1 [00:00<00:00,  3.98it/s]
100%|██████████| 1/1 [00:00<00:00,  4.28it/s]
100%|██████████| 1/1 [00:00<00:00,  3.00it/s]
100%|██████████| 1/1 [00:00<00:00,  3.08it/s]
100%|██████████| 1/1 [00:01<00:00,  1.17s/it]
100%|██████████| 1/1 [00:00<00:00,  3.08it/s]
100%|██████████| 1/1 [00:00<00:00,  2.93it/s]
100%|██████████| 1/1 [00:00<00:00,  2.95it/s]
100%|██████████| 1/1 [00:00<00:00,  3.00it/s]
100%|██████████| 1/1 [00:00<00:00,  1.11it/s]
100%|██████████| 1/1 [00:00<00:00,  3.60it/s]
100%|██████████| 1/1 [00:00<00:00,  4.94it/s]
100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  3.02it/s]
100%|██████████| 1/1 [00:00<00:00,  5.18it/s]
100%|██████████| 1/1 [00:00<00:00,  5.09it/s]
100%|██████████| 1/1 [00:00<00:00,  5.56it/s]
100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
100%|██████████| 1/1 [00:00<00:00,  4.92it/s]
100%|██████████| 1/1 [00:00<00:00,  5.18it/s]
100%|██████████| 1/1 [00:00<00:00,  5.46it/s]
100%|██████████| 1/1 [00:00<00:00,  4.92it/s]
100%|██████████| 1/1 [00:00<00:00,  5.35it/s]
100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
100%|██████████| 1/1 [00:00<00:00,  5.35it/s]
100%|██████████| 1/1 [00:00<00:00,  3.17it/s]
100%|██████████| 1/1 [00:00<00:00,  5.49it/s]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.39it/s]
100%|██████████| 1/1 [00:00<00:00,  5.52it/s]
100%|██████████| 1/1 [00:00<00:00,  5.22it/s]
100%|██████████| 1/1 [00:00<00:00,  5.04it/s]
100%|██████████| 1/1 [00:00<00:00,  5.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.19it/s]
100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
100%|██████████| 1/1 [00:00<00:00,  4.42it/s]
100%|██████████| 1/1 [00:00<00:00,  5.29it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  4.81it/s]
100%|██████████| 1/1 [00:00<00:00,  5.11it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.775795,1.000000,0.936047,1.000000,0.927961,1
2,Random Forest,0.730331,0.941648,0.936271,1.000000,0.902063,2
1,Decision Tree,0.626695,0.936168,0.944057,1.000000,0.876730,3
4,MLP,0.545602,0.547306,0.937055,1.000000,0.757491,4
3,XGBoost,0.662297,0.000000,0.948178,1.000000,0.652619,5

====================================================================================================
REPETITION 11/20 | seed=52
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
100%|██████████| 1/1 [00:00<00:00,  3.26it/s]
100%|██████████| 1/1 [00:00<00:00,  4.92it/s]
100%|██████████| 1/1 [00:00<00:00,  4.16it/s]
100%|██████████| 1/1 [00:00<00:00,  1.35it/s]
100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
100%|██████████| 1/1 [00:00<00:00,  4.45it/s]
100%|██████████| 1/1 [00:00<00:00,  4.33it/s]
100%|██████████| 1/1 [00:00<00:00,  4.91it/s]
100%|██████████| 1/1 [00:00<00:00,  4.88it/s]
100%|██████████| 1/1 [00:00<00:00,  5.03it/s]
100%|██████████| 1/1 [00:00<00:00,  4.71it/s]
100%|██████████| 1/1 [00:00<00:00,  4.86it/s]
100%|██████████| 1/1 [00:00<00:00,  5.03it/s]
100%|██████████| 1/1 [00:00<00:00,  5.02it/s]
100%|██████████| 1/1 [00:00<00:00,  5.02it/s]
100%|██████████| 1/1 [00:00<00:00,  4.54it/s]
100%|██████████| 1/1 [00:00<00:00,  4.65it/s]
100%|██████████| 1/1 [00:00<00:00,  4.71it/s]
100%|██████████| 1/1 [00:00<00:00,  4.06it/s]
100%|██████████| 1/1 [00:00<00:00,  4.58it/s]
100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
100%|██████████| 1/1 [00:00<00:00,  6.66it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  6.83it/s]
100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
100%|██████████| 1/1 [00:00<00:00,  4.97it/s]
100%|██████████| 1/1 [00:00<00:00,  4.43it/s]
100%|██████████| 1/1 [00:01<00:00,  1.49s/it]
100%|██████████| 1/1 [00:00<00:00,  4.76it/s]
100%|██████████| 1/1 [00:00<00:00,  4.42it/s]
100%|██████████| 1/1 [00:00<00:00,  4.82it/s]
100%|██████████| 1/1 [00:00<00:00,  4.90it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
100%|██████████| 1/1 [00:00<00:00,  4.97it/s]
100%|██████████| 1/1 [00:00<00:00,  4.53it/s]
100%|██████████| 1/1 [00:00<00:00,  4.65it/s]
100%|██████████| 1/1 [00:00<00:00,  4.20it/s]
100%|██████████| 1/1 [00:00<00:00,  4.41it/s]
100%|██████████| 1/1 [00:00<00:00,  4.24it/s]
100%|██████████| 1/1 [00:00<00:00,  4.28it/s]
100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
100%|██████████| 1/1 [00:00<00:00,  6.17it/s]
100%|██████████| 1/1 [00:00<00:00,  6.67it/s]
100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.94it/s]
100%|██████████| 1/1 [00:00<00:00,  4.21it/s]
100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
100%|██████████| 1/1 [00:00<00:00,  5.96it/s]
100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
100%|██████████| 1/1 [00:00<00:00,  6.81it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  2.58it/s]
100%|██████████| 1/1 [00:00<00:00,  2.46it/s]
100%|██████████| 1/1 [00:00<00:00,  1.75it/s]
100%|██████████| 1/1 [00:00<00:00,  1.74it/s]
100%|██████████| 1/1 [00:01<00:00,  1.59s/it]
100%|██████████| 1/1 [00:00<00:00,  1.66it/s]
100%|██████████| 1/1 [00:00<00:00,  1.75it/s]
100%|██████████| 1/1 [00:06<00:00,  6.37s/it]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  1.69it/s]
100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
100%|██████████| 1/1 [00:00<00:00,  1.75it/s]
100%|██████████| 1/1 [00:00<00:00,  1.80it/s]
100%|██████████| 1/1 [00:00<00:00,  1.80it/s]
100%|██████████| 1/1 [00:00<00:00,  1.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.03it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.67it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
100%|██████████| 1/1 [00:00<00:00,  5.79it/s]
100%|██████████| 1/1 [00:00<00:00,  4.42it/s]
100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
100%|██████████| 1/1 [00:00<00:00,  5.89it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
100%|██████████| 1/1 [00:00<00:00,  5.91it/s]
100%|██████████| 1/1 [00:00<00:00,  5.35it/s]
100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
100%|██████████| 1/1 [00:00<00:00,  5.91it/s]
100%|██████████| 1/1 [00:00<00:00,  6.03it/s]
100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
100%|██████████| 1/1 [00:00<00:00,  1.89it/s]
100%|██████████| 1/1 [00:00<00:00,  5.89it/s]
100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
100%|██████████| 1/1 [00:00<00:00,  5.46it/s]
100%|██████████| 1/1 [00:00<00:00,  5.96it/s]
100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  5.76it/s]
100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
100%|██████████| 1/1 [00:00<00:00,  5.97it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
100%|██████████| 1/1 [00:00<00:00,  5.18it/s]
100%|██████████| 1/1 [00:00<00:00,  5.42it/s]
100%|██████████| 1/1 [00:00<00:00,  1.89it/s]
100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
100%|██████████| 1/1 [00:00<00:00,  5.35it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  4.83it/s]
100%|██████████| 1/1 [00:00<00:00,  5.39it/s]
100%|██████████| 1/1 [00:00<00:00,  4.71it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.41it/s]
100%|██████████| 1/1 [00:00<00:00,  4.47it/s]
100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
100%|██████████| 1/1 [00:00<00:00,  5.46it/s]
100%|██████████| 1/1 [00:00<00:00,  5.04it/s]
100%|██████████| 1/1 [00:01<00:00,  1.90s/it]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  5.29it/s]
100%|██████████| 1/1 [00:00<00:00,  5.41it/s]
100%|██████████| 1/1 [00:00<00:00,  5.26it/s]
100%|██████████| 1/1 [00:00<00:00,  5.43it/s]
100%|██████████| 1/1 [00:00<00:00,  4.48it/s]
100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  3.31it/s]
100%|██████████| 1/1 [00:00<00:00,  3.44it/s]
100%|██████████| 1/1 [00:00<00:00,  3.33it/s]
100%|██████████| 1/1 [00:00<00:00,  3.33it/s]
100%|██████████| 1/1 [00:00<00:00,  2.91it/s]
100%|██████████| 1/1 [00:00<00:00,  3.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.04it/s]
100%|██████████| 1/1 [00:00<00:00,  2.81it/s]
100%|██████████| 1/1 [00:00<00:00,  3.51it/s]
100%|██████████| 1/1 [00:00<00:00,  3.00it/s]
100%|██████████| 1/1 [00:00<00:00,  3.04it/s]
100%|██████████| 1/1 [00:00<00:00,  2.98it/s]
100%|██████████| 1/1 [00:00<00:00,  2.82it/s]
100%|██████████| 1/1 [00:00<00:00,  3.38it/s]
100%|██████████| 1/1 [00:00<00:00,  3.71it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  4.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  4.39it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  3.64it/s]
100%|██████████| 1/1 [00:00<00:00,  4.79it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  5.02it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  3.05it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.23it/s]
100%|██████████| 1/1 [00:00<00:00,  5.33it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.795443,1.000000,0.938091,1.000000,0.933384,1
2,Random Forest,0.774580,0.941051,0.941911,1.000000,0.914385,2
1,Decision Tree,0.719769,0.902526,0.945664,1.000000,0.891990,3
4,MLP,0.581364,0.644664,0.940935,1.000000,0.791741,4
3,XGBoost,0.684748,0.000000,0.945966,1.000000,0.657678,5

====================================================================================================
REPETITION 12/20 | seed=53
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
100%|██████████| 1/1 [00:00<00:00,  1.94it/s]
100%|██████████| 1/1 [00:00<00:00,  1.23it/s]
100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
100%|██████████| 1/1 [00:00<00:00,  2.99it/s]
100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
100%|██████████| 1/1 [00:00<00:00,  4.40it/s]
100%|██████████| 1/1 [00:00<00:00,  4.94it/s]
100%|██████████| 1/1 [00:00<00:00,  5.12it/s]
100%|██████████| 1/1 [00:00<00:00,  5.15it/s]
100%|██████████| 1/1 [00:00<00:00,  4.56it/s]
100%|██████████| 1/1 [00:00<00:00,  4.52it/s]
100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  5.13it/s]
100%|██████████| 1/1 [00:00<00:00,  4.44it/s]
100%|██████████| 1/1 [00:00<00:00,  4.21it/s]
100%|██████████| 1/1 [00:00<00:00,  4.86it/s]
100%|██████████| 1/1 [00:00<00:00,  3.87it/s]
100%|██████████| 1/1 [00:00<00:00,  5.07it/s]
100%|██████████| 1/1 [00:00<00:00,  4.49it/s]
100%|██████████| 1/1 [00:00<00:00,  4.54it/s]
100%|██████████| 1/1 [00:00<00:00,  5.01it/s]
100%|██████████| 1/1 [00:00<00:00,  4.97it/s]
100%|██████████| 1/1 [00:00<00:00,  4.82it/s]
100%|██████████| 1/1 [00:00<00:00,  4.83it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
100%|██████████| 1/1 [00:00<00:00,  6.68it/s]
100%|██████████| 1/1 [00:00<00:00,  2.77it/s]
100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
100%|██████████| 1/1 [00:00<00:00,  2.90it/s]
100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
100%|██████████| 1/1 [00:00<00:00,  4.41it/s]
100%|██████████| 1/1 [00:00<00:00,  4.30it/s]
100%|██████████| 1/1 [00:00<00:00,  4.54it/s]
100%|██████████| 1/1 [00:00<00:00,  4.93it/s]
100%|██████████| 1/1 [00:00<00:00,  3.36it/s]
100%|██████████| 1/1 [00:00<00:00,  4.32it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:00<00:00,  2.17it/s]
100%|██████████| 1/1 [00:00<00:00,  1.88it/s]
100%|██████████| 1/1 [00:00<00:00,  1.75it/s]
100%|██████████| 1/1 [00:00<00:00,  1.73it/s]
100%|██████████| 1/1 [00:00<00:00,  1.75it/s]
100%|██████████| 1/1 [00:00<00:00,  1.78it/s]
100%|██████████| 1/1 [00:00<00:00,  1.77it/s]
100%|██████████| 1/1 [00:00<00:00,  1.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.18it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.45it/s]
100%|██████████| 1/1 [00:00<00:00,  2.67it/s]
100%|██████████| 1/1 [00:00<00:00,  2.57it/s]
100%|██████████| 1/1 [00:00<00:00,  2.38it/s]
100%|██████████| 1/1 [00:00<00:00,  2.67it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
100%|██████████| 1/1 [00:00<00:00,  5.11it/s]
100%|██████████| 1/1 [00:00<00:00,  5.60it/s]
100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
100%|██████████| 1/1 [00:00<00:00,  2.03it/s]
100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
100%|██████████| 1/1 [00:00<00:00,  5.97it/s]
100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
100%|██████████| 1/1 [00:00<00:00,  6.03it/s]
100%|██████████| 1/1 [00:00<00:00,  1.80it/s]
100%|██████████| 1/1 [00:00<00:00,  5.62it/s]
100%|██████████| 1/1 [00:00<00:00,  5.91it/s]
100%|██████████| 1/1 [00:00<00:00,  5.99it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  5.21it/s]
100%|██████████| 1/1 [00:00<00:00,  5.70it/s]
100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
100%|██████████| 1/1 [00:00<00:00,  5.43it/s]
100%|██████████| 1/1 [00:00<00:00,  5.82it/s]
100%|██████████| 1/1 [00:00<00:00,  5.56it/s]
100%|██████████| 1/1 [00:00<00:00,  3.04it/s]
100%|██████████| 1/1 [00:00<00:00,  4.16it/s]
100%|██████████| 1/1 [00:00<00:00,  3.59it/s]
100%|██████████| 1/1 [00:00<00:00,  3.47it/s]
100%|██████████| 1/1 [00:00<00:00,  3.14it/s]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:00<00:00,  2.75it/s]
100%|██████████| 1/1 [00:00<00:00,  2.96it/s]
100%|██████████| 1/1 [00:00<00:00,  1.17it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
100%|██████████| 1/1 [00:00<00:00,  4.86it/s]
100%|██████████| 1/1 [00:00<00:00,  5.52it/s]
100%|██████████| 1/1 [00:00<00:00,  5.41it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
100%|██████████| 1/1 [00:00<00:00,  5.03it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.56it/s]
100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
100%|██████████| 1/1 [00:00<00:00,  5.60it/s]
100%|██████████| 1/1 [00:00<00:00,  5.29it/s]
100%|██████████| 1/1 [00:00<00:00,  5.04it/s]
100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  4.79it/s]
100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.27it/s]
100%|██████████| 1/1 [00:00<00:00,  5.42it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.00it/s]
100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
100%|██████████| 1/1 [00:00<00:00,  4.28it/s]
100%|██████████| 1/1 [00:00<00:00,  2.96it/s]
100%|██████████| 1/1 [00:00<00:00,  2.94it/s]
100%|██████████| 1/1 [00:00<00:00,  3.01it/s]
100%|██████████| 1/1 [00:00<00:00,  3.13it/s]
100%|██████████| 1/1 [00:00<00:00,  2.89it/s]
100%|██████████| 1/1 [00:00<00:00,  3.43it/s]
100%|██████████| 1/1 [00:00<00:00,  2.92it/s]
100%|██████████| 1/1 [00:00<00:00,  4.33it/s]
100%|██████████| 1/1 [00:00<00:00,  2.96it/s]
100%|██████████| 1/1 [00:00<00:00,  1.24it/s]
100%|██████████| 1/1 [00:00<00:00,  3.44it/s]
100%|██████████| 1/1 [00:00<00:00,  3.78it/s]
100%|██████████| 1/1 [00:00<00:00,  3.20it/s]
100%|██████████| 1/1 [00:00<00:00,  3.95it/s]
100%|██████████| 1/1 [00:00<00:00,  4.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.23it/s]
100%|██████████| 1/1 [00:00<00:00,  5.27it/s]
100%|██████████| 1/1 [00:00<00:00,  3.02it/s]
100%|██████████| 1/1 [00:00<00:00,  4.64it/s]
100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
100%|██████████| 1/1 [00:00<00:00,  4.87it/s]
100%|██████████| 1/1 [00:00<00:00,  5.00it/s]
100%|██████████| 1/1 [00:00<00:00,  5.41it/s]
100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
100%|██████████| 1/1 [00:00<00:00,  5.35it/s]
100%|██████████| 1/1 [00:00<00:00,  5.35it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.823680,1.000000,0.935705,1.000000,0.939846,1
2,Random Forest,0.769480,0.942709,0.943354,1.000000,0.913886,2
1,Decision Tree,0.656506,0.869689,0.935666,1.000000,0.865465,3
4,MLP,0.550365,0.541806,0.934829,1.000000,0.756750,4
3,XGBoost,0.699631,0.000000,0.944492,1.000000,0.661031,5

====================================================================================================
REPETITION 13/20 | seed=54
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
100%|██████████| 1/1 [00:00<00:00,  2.89it/s]
100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
100%|██████████| 1/1 [00:01<00:00,  1.05s/it]
100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
100%|██████████| 1/1 [00:00<00:00,  2.34it/s]
100%|██████████| 1/1 [00:00<00:00,  6.21it/s]
100%|██████████| 1/1 [00:00<00:00,  5.41it/s]
100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
100%|██████████| 1/1 [00:00<00:00,  3.65it/s]
100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
100%|██████████| 1/1 [00:00<00:00,  2.58it/s]
100%|██████████| 1/1 [00:00<00:00,  4.76it/s]
100%|██████████| 1/1 [00:00<00:00,  4.72it/s]
100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
100%|██████████| 1/1 [00:00<00:00,  4.28it/s]
100%|██████████| 1/1 [00:00<00:00,  5.02it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  4.93it/s]
100%|██████████| 1/1 [00:00<00:00,  4.07it/s]
100%|██████████| 1/1 [00:00<00:00,  4.38it/s]
100%|██████████| 1/1 [00:00<00:00,  4.80it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
100%|██████████| 1/1 [00:00<00:00,  3.30it/s]
100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
100%|██████████| 1/1 [00:00<00:00,  6.11it/s]
100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
100%|██████████| 1/1 [00:00<00:00,  2.21it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  2.68it/s]
100%|██████████| 1/1 [00:00<00:00,  2.66it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.47it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.67it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.35it/s]
100%|██████████| 1/1 [00:00<00:00,  1.70it/s]
100%|██████████| 1/1 [00:00<00:00,  1.78it/s]
100%|██████████| 1/1 [00:00<00:00,  1.76it/s]
100%|██████████| 1/1 [00:00<00:00,  1.73it/s]
100%|██████████| 1/1 [00:00<00:00,  1.87it/s]
100%|██████████| 1/1 [00:00<00:00,  1.74it/s]
100%|██████████| 1/1 [00:00<00:00,  1.78it/s]
100%|██████████| 1/1 [00:00<00:00,  1.98it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.67it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.57it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.50it/s]
100%|██████████| 1/1 [00:00<00:00,  2.58it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:00<00:00,  1.22it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  5.50it/s]
100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
100%|██████████| 1/1 [00:00<00:00,  5.96it/s]
100%|██████████| 1/1 [00:01<00:00,  1.81s/it]
100%|██████████| 1/1 [00:00<00:00,  3.65it/s]
100%|██████████| 1/1 [00:01<00:00,  1.14s/it]
100%|██████████| 1/1 [00:00<00:00,  3.24it/s]
100%|██████████| 1/1 [00:00<00:00,  3.88it/s]
100%|██████████| 1/1 [00:00<00:00,  3.34it/s]
100%|██████████| 1/1 [00:00<00:00,  3.84it/s]
100%|██████████| 1/1 [00:00<00:00,  4.11it/s]
100%|██████████| 1/1 [00:00<00:00,  3.65it/s]
100%|██████████| 1/1 [00:00<00:00,  4.36it/s]
100%|██████████| 1/1 [00:00<00:00,  2.84it/s]
100%|██████████| 1/1 [00:00<00:00,  2.82it/s]
100%|██████████| 1/1 [00:00<00:00,  2.89it/s]
100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
100%|██████████| 1/1 [00:00<00:00,  3.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
100%|██████████| 1/1 [00:00<00:00,  5.12it/s]
100%|██████████| 1/1 [00:00<00:00,  5.82it/s]
100%|██████████| 1/1 [00:00<00:00,  2.01it/s]
100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  1.46it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  2.02it/s]
100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
100%|██████████| 1/1 [00:00<00:00,  5.98it/s]
100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  5.76it/s]
100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  4.24it/s]
100%|██████████| 1/1 [00:00<00:00,  4.68it/s]
100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
100%|██████████| 1/1 [00:00<00:00,  5.60it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  4.69it/s]
100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
100%|██████████| 1/1 [00:00<00:00,  5.35it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  5.22it/s]
100%|██████████| 1/1 [00:00<00:00,  4.90it/s]
100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
100%|██████████| 1/1 [00:00<00:00,  4.86it/s]
100%|██████████| 1/1 [00:00<00:00,  5.34it/s]
100%|██████████| 1/1 [00:00<00:00,  2.07it/s]
100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
100%|██████████| 1/1 [00:00<00:00,  4.81it/s]
100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
100%|██████████| 1/1 [00:00<00:00,  5.22it/s]
100%|██████████| 1/1 [00:00<00:00,  4.91it/s]
100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
100%|██████████| 1/1 [00:00<00:00,  5.43it/s]
100%|██████████| 1/1 [00:00<00:00,  5.29it/s]
100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
100%|██████████| 1/1 [00:00<00:00,  4.57it/s]
100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
100%|██████████| 1/1 [00:00<00:00,  5.46it/s]
100%|██████████| 1/1 [00:00<00:00,  5.21it/s]
100%|██████████| 1/1 [00:00<00:00,  5.45it/s]
100%|██████████| 1/1 [00:00<00:00,  4.92it/s]
100%|██████████| 1/1 [00:00<00:00,  5.39it/s]
100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
100%|██████████| 1/1 [00:00<00:00,  2.84it/s]
100%|██████████| 1/1 [00:00<00:00,  5.13it/s]
100%|██████████| 1/1 [00:00<00:00,  4.98it/s]
100%|██████████| 1/1 [00:00<00:00,  5.23it/s]
100%|██████████| 1/1 [00:00<00:00,  5.03it/s]
100%|██████████| 1/1 [00:00<00:00,  5.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.18it/s]
100%|██████████| 1/1 [00:00<00:00,  4.73it/s]
100%|██████████| 1/1 [00:00<00:00,  3.43it/s]
100%|██████████| 1/1 [00:00<00:00,  4.16it/s]
100%|██████████| 1/1 [00:00<00:00,  2.85it/s]
100%|██████████| 1/1 [00:00<00:00,  3.09it/s]
100%|██████████| 1/1 [00:00<00:00,  3.02it/s]
100%|██████████| 1/1 [00:00<00:00,  2.91it/s]
100%|██████████| 1/1 [00:00<00:00,  3.40it/s]
100%|██████████| 1/1 [00:00<00:00,  3.29it/s]
100%|██████████| 1/1 [00:00<00:00,  3.02it/s]
100%|██████████| 1/1 [00:00<00:00,  3.00it/s]
100%|██████████| 1/1 [00:00<00:00,  1.34it/s]
100%|██████████| 1/1 [00:00<00:00,  3.76it/s]
100%|██████████| 1/1 [00:00<00:00,  3.38it/s]
100%|██████████| 1/1 [00:00<00:00,  4.26it/s]
100%|██████████| 1/1 [00:00<00:00,  3.51it/s]
100%|██████████| 1/1 [00:00<00:00,  5.39it/s]
100%|██████████| 1/1 [00:00<00:00,  5.51it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.804923,0.991954,0.945229,1.000000,0.935527,1
2,Random Forest,0.766983,0.952175,0.941932,1.000000,0.915272,2
1,Decision Tree,0.707488,1.000000,0.942225,1.000000,0.912428,3
4,MLP,0.604141,0.456012,0.942912,1.000000,0.750766,4
3,XGBoost,0.698232,0.000000,0.943034,1.000000,0.660316,5

====================================================================================================
REPETITION 14/20 | seed=55
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
100%|██████████| 1/1 [00:00<00:00,  6.22it/s]
100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.23it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  6.51it/s]
100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
100%|██████████| 1/1 [00:01<00:00,  1.52s/it]
100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
100%|██████████| 1/1 [00:00<00:00,  6.51it/s]
100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
100%|██████████| 1/1 [00:00<00:00,  6.28it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
100%|██████████| 1/1 [00:00<00:00,  6.68it/s]
100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
100%|██████████| 1/1 [00:00<00:00,  6.10it/s]
100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
100%|██████████| 1/1 [00:00<00:00,  6.83it/s]
100%|██████████| 1/1 [00:00<00:00,  6.68it/s]
100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
100%|██████████| 1/1 [00:00<00:00,  6.14it/s]
100%|██████████| 1/1 [00:00<00:00,  4.25it/s]
100%|██████████| 1/1 [00:00<00:00,  4.41it/s]
100%|██████████| 1/1 [00:00<00:00,  5.01it/s]
100%|██████████| 1/1 [00:00<00:00,  5.23it/s]
100%|██████████| 1/1 [00:00<00:00,  4.43it/s]
100%|██████████| 1/1 [00:00<00:00,  4.58it/s]
100%|██████████| 1/1 [00:02<00:00,  2.77s/it]
100%|██████████| 1/1 [00:00<00:00,  3.55it/s]
100%|██████████| 1/1 [00:00<00:00,  4.00it/s]
100%|██████████| 1/1 [00:00<00:00,  5.21it/s]
100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
100%|██████████| 1/1 [00:00<00:00,  6.29it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.45it/s]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.25it/s]
100%|██████████| 1/1 [00:02<00:00,  2.44s/it]
100%|██████████| 1/1 [00:00<00:00,  1.76it/s]
100%|██████████| 1/1 [00:00<00:00,  1.81it/s]
100%|██████████| 1/1 [00:00<00:00,  1.66it/s]
100%|██████████| 1/1 [00:01<00:00,  1.41s/it]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.41it/s]
100%|██████████| 1/1 [00:00<00:00,  2.67it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.01it/s]
100%|██████████| 1/1 [00:00<00:00,  2.57it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.38it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:01<00:00,  1.36s/it]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.01it/s]
100%|██████████| 1/1 [00:00<00:00,  1.77it/s]
100%|██████████| 1/1 [00:00<00:00,  1.77it/s]
100%|██████████| 1/1 [00:00<00:00,  1.65it/s]
100%|██████████| 1/1 [00:00<00:00,  1.82it/s]
100%|██████████| 1/1 [00:00<00:00,  1.81it/s]
100%|██████████| 1/1 [00:00<00:00,  1.76it/s]
100%|██████████| 1/1 [00:00<00:00,  1.68it/s]
100%|██████████| 1/1 [00:00<00:00,  1.99it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
100%|██████████| 1/1 [00:01<00:00,  1.58s/it]
100%|██████████| 1/1 [00:00<00:00,  5.05it/s]
100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
100%|██████████| 1/1 [00:00<00:00,  5.06it/s]
100%|██████████| 1/1 [00:00<00:00,  5.73it/s]
100%|██████████| 1/1 [00:00<00:00,  5.92it/s]
100%|██████████| 1/1 [00:00<00:00,  3.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
100%|██████████| 1/1 [00:00<00:00,  3.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
100%|██████████| 1/1 [00:00<00:00,  5.73it/s]
100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
100%|██████████| 1/1 [00:00<00:00,  5.79it/s]
100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
100%|██████████| 1/1 [00:00<00:00,  5.34it/s]
100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.79it/s]
100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
100%|██████████| 1/1 [00:00<00:00,  5.20it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
100%|██████████| 1/1 [00:00<00:00,  5.45it/s]
100%|██████████| 1/1 [00:00<00:00,  3.62it/s]
100%|██████████| 1/1 [00:00<00:00,  3.85it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.86it/s]
100%|██████████| 1/1 [00:00<00:00,  2.87it/s]
100%|██████████| 1/1 [00:00<00:00,  2.97it/s]
100%|██████████| 1/1 [00:00<00:00,  3.92it/s]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:00<00:00,  2.80it/s]
100%|██████████| 1/1 [00:00<00:00,  2.76it/s]
100%|██████████| 1/1 [00:00<00:00,  3.16it/s]
100%|██████████| 1/1 [00:00<00:00,  3.89it/s]
100%|██████████| 1/1 [00:00<00:00,  2.95it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.68it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
100%|██████████| 1/1 [00:00<00:00,  5.05it/s]
100%|██████████| 1/1 [00:00<00:00,  4.41it/s]
100%|██████████| 1/1 [00:00<00:00,  4.90it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  5.07it/s]
100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
100%|██████████| 1/1 [00:00<00:00,  4.82it/s]
100%|██████████| 1/1 [00:00<00:00,  5.57it/s]
100%|██████████| 1/1 [00:00<00:00,  5.21it/s]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:01<00:00,  1.85s/it]
100%|██████████| 1/1 [00:00<00:00,  3.09it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  3.11it/s]
100%|██████████| 1/1 [00:00<00:00,  4.02it/s]
100%|██████████| 1/1 [00:00<00:00,  3.22it/s]
100%|██████████| 1/1 [00:00<00:00,  3.01it/s]
100%|██████████| 1/1 [00:00<00:00,  3.00it/s]
100%|██████████| 1/1 [00:00<00:00,  3.13it/s]
100%|██████████| 1/1 [00:00<00:00,  2.80it/s]
100%|██████████| 1/1 [00:00<00:00,  2.98it/s]
100%|██████████| 1/1 [00:00<00:00,  2.93it/s]
100%|██████████| 1/1 [00:00<00:00,  3.55it/s]
100%|██████████| 1/1 [00:00<00:00,  3.62it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:01<00:00,  1.64s/it]
100%|██████████| 1/1 [00:00<00:00,  5.04it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  4.20it/s]
100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
100%|██████████| 1/1 [00:00<00:00,  4.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
100%|██████████| 1/1 [00:00<00:00,  5.22it/s]
100%|██████████| 1/1 [00:00<00:00,  5.46it/s]
100%|██████████| 1/1 [00:00<00:00,  4.97it/s]
100%|██████████| 1/1 [00:00<00:00,  5.20it/s]
100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.20it/s]
100%|██████████| 1/1 [00:00<00:00,  3.23it/s]
100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
100%|██████████| 1/1 [00:00<00:00,  5.29it/s]
100%|██████████| 1/1 [00:00<00:00,  4.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.09it/s]
100%|██████████| 1/1 [00:00<00:00,  5.57it/s]
100%|██████████| 1/1 [00:00<00:00,  5.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.30it/s]
100%|██████████| 1/1 [00:00<00:00,  1.13it/s]
100%|██████████| 1/1 [00:00<00:00,  5.49it/s]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  5.29it/s]
100%|██████████| 1/1 [00:00<00:00,  5.03it/s]
100%|██████████| 1/1 [00:00<00:00,  4.81it/s]
100%|██████████| 1/1 [00:00<00:00,  5.45it/s]
100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  5.41it/s]
100%|██████████| 1/1 [00:00<00:00,  3.97it/s]
100%|██████████| 1/1 [00:00<00:00,  4.00it/s]
100%|██████████| 1/1 [00:01<00:00,  1.30s/it]
100%|██████████| 1/1 [00:00<00:00,  4.17it/s]
100%|██████████| 1/1 [00:00<00:00,  2.93it/s]
100%|██████████| 1/1 [00:00<00:00,  3.00it/s]
100%|██████████| 1/1 [00:00<00:00,  3.99it/s]
100%|██████████| 1/1 [00:00<00:00,  2.93it/s]
100%|██████████| 1/1 [00:00<00:00,  2.80it/s]
100%|██████████| 1/1 [00:00<00:00,  3.04it/s]
100%|██████████| 1/1 [00:00<00:00,  3.35it/s]
100%|██████████| 1/1 [00:00<00:00,  3.29it/s]
100%|██████████| 1/1 [00:00<00:00,  3.61it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.787697,1.000000,0.930215,1.000000,0.929478,1
2,Random Forest,0.755448,0.958069,0.936657,1.000000,0.912544,2
1,Decision Tree,0.653180,0.875665,0.936523,1.000000,0.866342,3
4,MLP,0.602918,0.645832,0.936896,1.000000,0.796411,4
3,XGBoost,0.676855,0.000000,0.942835,1.000000,0.654923,5

====================================================================================================
REPETITION 15/20 | seed=56
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
100%|██████████| 1/1 [00:00<00:00,  6.21it/s]
100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
100%|██████████| 1/1 [00:00<00:00,  6.14it/s]
100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
100%|██████████| 1/1 [00:00<00:00,  6.67it/s]
100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
100%|██████████| 1/1 [00:00<00:00,  2.04it/s]
100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
100%|██████████| 1/1 [00:00<00:00,  5.56it/s]
100%|██████████| 1/1 [00:00<00:00,  6.12it/s]
100%|██████████| 1/1 [00:00<00:00,  6.68it/s]
100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
100%|██████████| 1/1 [00:00<00:00,  1.43it/s]
100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
100%|██████████| 1/1 [00:00<00:00,  5.99it/s]
100%|██████████| 1/1 [00:00<00:00,  6.68it/s]
100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
100%|██████████| 1/1 [00:00<00:00,  6.85it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
100%|██████████| 1/1 [00:00<00:00,  3.86it/s]
100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
100%|██████████| 1/1 [00:00<00:00,  6.67it/s]
100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
100%|██████████| 1/1 [00:00<00:00,  5.97it/s]
100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
100%|██████████| 1/1 [00:00<00:00,  6.17it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.68it/s]
100%|██████████| 1/1 [00:00<00:00,  2.57it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.66it/s]
100%|██████████| 1/1 [00:00<00:00,  2.67it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.57it/s]
100%|██████████| 1/1 [00:00<00:00,  2.66it/s]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.10it/s]
100%|██████████| 1/1 [00:00<00:00,  1.71it/s]
100%|██████████| 1/1 [00:00<00:00,  1.45it/s]
100%|██████████| 1/1 [00:00<00:00,  1.66it/s]
100%|██████████| 1/1 [00:00<00:00,  1.82it/s]
100%|██████████| 1/1 [00:00<00:00,  1.01it/s]
100%|██████████| 1/1 [00:00<00:00,  1.15it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.43it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.57it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.50it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.45it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.50it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  6.21it/s]
100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
100%|██████████| 1/1 [00:00<00:00,  5.79it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  5.96it/s]
100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
100%|██████████| 1/1 [00:00<00:00,  3.41it/s]
100%|██████████| 1/1 [00:00<00:00,  5.79it/s]
100%|██████████| 1/1 [00:00<00:00,  5.13it/s]
100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
100%|██████████| 1/1 [00:00<00:00,  5.70it/s]
100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
100%|██████████| 1/1 [00:00<00:00,  5.26it/s]
100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
100%|██████████| 1/1 [00:00<00:00,  2.13it/s]
100%|██████████| 1/1 [00:00<00:00,  2.96it/s]
100%|██████████| 1/1 [00:00<00:00,  2.81it/s]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  3.32it/s]
100%|██████████| 1/1 [00:00<00:00,  3.64it/s]
100%|██████████| 1/1 [00:00<00:00,  2.86it/s]
100%|██████████| 1/1 [00:00<00:00,  1.58it/s]
100%|██████████| 1/1 [00:00<00:00,  2.90it/s]
100%|██████████| 1/1 [00:00<00:00,  3.17it/s]
100%|██████████| 1/1 [00:00<00:00,  3.55it/s]
100%|██████████| 1/1 [00:00<00:00,  3.44it/s]
100%|██████████| 1/1 [00:00<00:00,  3.31it/s]
100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
100%|██████████| 1/1 [00:00<00:00,  5.51it/s]
100%|██████████| 1/1 [00:00<00:00,  5.91it/s]
100%|██████████| 1/1 [00:00<00:00,  5.75it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  5.73it/s]
100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
100%|██████████| 1/1 [00:00<00:00,  4.65it/s]
100%|██████████| 1/1 [00:00<00:00,  5.34it/s]
100%|██████████| 1/1 [00:00<00:00,  5.21it/s]
100%|██████████| 1/1 [00:00<00:00,  5.11it/s]
100%|██████████| 1/1 [00:00<00:00,  5.20it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
100%|██████████| 1/1 [00:00<00:00,  5.45it/s]
100%|██████████| 1/1 [00:00<00:00,  5.17it/s]
100%|██████████| 1/1 [00:00<00:00,  5.22it/s]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  4.89it/s]
100%|██████████| 1/1 [00:00<00:00,  2.19it/s]
100%|██████████| 1/1 [00:00<00:00,  5.61it/s]
100%|██████████| 1/1 [00:00<00:00,  3.78it/s]
100%|██████████| 1/1 [00:00<00:00,  3.31it/s]
100%|██████████| 1/1 [00:00<00:00,  1.05it/s]
100%|██████████| 1/1 [00:00<00:00,  3.12it/s]
100%|██████████| 1/1 [00:00<00:00,  3.92it/s]
100%|██████████| 1/1 [00:00<00:00,  3.58it/s]
100%|██████████| 1/1 [00:00<00:00,  3.51it/s]
100%|██████████| 1/1 [00:00<00:00,  3.11it/s]
100%|██████████| 1/1 [00:00<00:00,  3.33it/s]
100%|██████████| 1/1 [00:00<00:00,  2.95it/s]
100%|██████████| 1/1 [00:00<00:00,  1.38it/s]
100%|██████████| 1/1 [00:00<00:00,  3.09it/s]
100%|██████████| 1/1 [00:00<00:00,  3.06it/s]
100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
100%|██████████| 1/1 [00:00<00:00,  5.26it/s]
100%|██████████| 1/1 [00:00<00:00,  4.67it/s]
100%|██████████| 1/1 [00:01<00:00,  1.63s/it]
100%|██████████| 1/1 [00:00<00:00,  5.26it/s]
100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  4.60it/s]
100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
100%|██████████| 1/1 [00:00<00:00,  4.61it/s]
100%|██████████| 1/1 [00:00<00:00,  5.46it/s]
100%|██████████| 1/1 [00:00<00:00,  5.15it/s]
100%|██████████| 1/1 [00:00<00:00,  5.15it/s]
100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  4.60it/s]
100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
100%|██████████| 1/1 [00:00<00:00,  3.25it/s]
100%|██████████| 1/1 [00:00<00:00,  3.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
100%|██████████| 1/1 [00:00<00:00,  5.05it/s]
100%|██████████| 1/1 [00:00<00:00,  5.22it/s]
100%|██████████| 1/1 [00:00<00:00,  5.15it/s]
100%|██████████| 1/1 [00:00<00:00,  4.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.27it/s]
100%|██████████| 1/1 [00:00<00:00,  2.27it/s]
100%|██████████| 1/1 [00:00<00:00,  4.71it/s]
100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.17it/s]
100%|██████████| 1/1 [00:00<00:00,  4.47it/s]
100%|██████████| 1/1 [00:00<00:00,  5.18it/s]
100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
100%|██████████| 1/1 [00:00<00:00,  5.22it/s]
100%|██████████| 1/1 [00:00<00:00,  3.90it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.778546,1.000000,0.930982,1.000000,0.927382,1
2,Random Forest,0.745291,0.961856,0.937329,1.000000,0.911119,2
1,Decision Tree,0.635834,0.922451,0.947548,1.000000,0.876458,3
4,MLP,0.577711,0.600389,0.940282,1.000000,0.779596,4
3,XGBoost,0.687840,0.000000,0.942899,1.000000,0.657685,5

====================================================================================================
REPETITION 16/20 | seed=57
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  4.63it/s]
100%|██████████| 1/1 [00:00<00:00,  4.53it/s]
100%|██████████| 1/1 [00:00<00:00,  4.71it/s]
100%|██████████| 1/1 [00:00<00:00,  2.44it/s]
100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
100%|██████████| 1/1 [00:00<00:00,  2.10it/s]
100%|██████████| 1/1 [00:00<00:00,  4.55it/s]
100%|██████████| 1/1 [00:00<00:00,  4.78it/s]
100%|██████████| 1/1 [00:00<00:00,  4.52it/s]
100%|██████████| 1/1 [00:00<00:00,  4.93it/s]
100%|██████████| 1/1 [00:00<00:00,  4.16it/s]
100%|██████████| 1/1 [00:00<00:00,  2.29it/s]
100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
100%|██████████| 1/1 [00:00<00:00,  6.67it/s]
100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
100%|██████████| 1/1 [00:00<00:00,  5.96it/s]
100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
100%|██████████| 1/1 [00:00<00:00,  6.09it/s]
100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
100%|██████████| 1/1 [00:00<00:00,  6.17it/s]
100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
100%|██████████| 1/1 [00:01<00:00,  1.42s/it]
100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
100%|██████████| 1/1 [00:00<00:00,  6.11it/s]
100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
100%|██████████| 1/1 [00:00<00:00,  6.68it/s]
100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
100%|██████████| 1/1 [00:00<00:00,  6.67it/s]
100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
100%|██████████| 1/1 [00:00<00:00,  6.65it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
100%|██████████| 1/1 [00:00<00:00,  5.95it/s]
100%|██████████| 1/1 [00:00<00:00,  5.94it/s]
100%|██████████| 1/1 [00:00<00:00,  6.51it/s]
100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
100%|██████████| 1/1 [00:00<00:00,  6.23it/s]
100%|██████████| 1/1 [00:00<00:00,  5.98it/s]
100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
100%|██████████| 1/1 [00:00<00:00,  6.35it/s]
100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
100%|██████████| 1/1 [00:00<00:00,  5.95it/s]
100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
100%|██████████| 1/1 [00:00<00:00,  6.06it/s]
100%|██████████| 1/1 [00:00<00:00,  6.67it/s]
100%|██████████| 1/1 [00:00<00:00,  6.22it/s]
100%|██████████| 1/1 [00:00<00:00,  5.95it/s]
100%|██████████| 1/1 [00:00<00:00,  4.34it/s]
100%|██████████| 1/1 [00:00<00:00,  4.07it/s]
100%|██████████| 1/1 [00:00<00:00,  4.71it/s]
100%|██████████| 1/1 [00:00<00:00,  5.17it/s]
100%|██████████| 1/1 [00:00<00:00,  4.44it/s]
100%|██████████| 1/1 [00:00<00:00,  4.80it/s]
100%|██████████| 1/1 [00:00<00:00,  4.90it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
100%|██████████| 1/1 [00:00<00:00,  4.88it/s]
100%|██████████| 1/1 [00:00<00:00,  4.04it/s]
100%|██████████| 1/1 [00:00<00:00,  4.28it/s]
100%|██████████| 1/1 [00:00<00:00,  4.99it/s]
100%|██████████| 1/1 [00:00<00:00,  5.04it/s]
100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  1.75it/s]
100%|██████████| 1/1 [00:00<00:00,  5.15it/s]
100%|██████████| 1/1 [00:00<00:00,  5.03it/s]
100%|██████████| 1/1 [00:00<00:00,  4.40it/s]
100%|██████████| 1/1 [00:00<00:00,  4.26it/s]
100%|██████████| 1/1 [00:00<00:00,  4.17it/s]
100%|██████████| 1/1 [00:00<00:00,  4.39it/s]
100%|██████████| 1/1 [00:00<00:00,  5.43it/s]
100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
100%|██████████| 1/1 [00:00<00:00,  6.69it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  2.68it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.45it/s]
100%|██████████| 1/1 [00:00<00:00,  1.70it/s]
100%|██████████| 1/1 [00:00<00:00,  1.74it/s]
100%|██████████| 1/1 [00:00<00:00,  1.48it/s]
100%|██████████| 1/1 [00:00<00:00,  1.75it/s]
100%|██████████| 1/1 [00:00<00:00,  1.78it/s]
100%|██████████| 1/1 [00:00<00:00,  1.76it/s]
100%|██████████| 1/1 [00:00<00:00,  1.78it/s]
100%|██████████| 1/1 [00:00<00:00,  1.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.05it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.14it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:00<00:00,  2.47it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.40it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
100%|██████████| 1/1 [00:08<00:00,  8.65s/it]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  1.92it/s]
100%|██████████| 1/1 [00:00<00:00,  2.39it/s]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.50it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
100%|██████████| 1/1 [00:00<00:00,  5.72it/s]
100%|██████████| 1/1 [00:00<00:00,  5.65it/s]
100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
100%|██████████| 1/1 [00:00<00:00,  3.41it/s]
100%|██████████| 1/1 [00:00<00:00,  3.88it/s]
100%|██████████| 1/1 [00:00<00:00,  3.83it/s]
100%|██████████| 1/1 [00:00<00:00,  3.37it/s]
100%|██████████| 1/1 [00:00<00:00,  3.94it/s]
100%|██████████| 1/1 [00:00<00:00,  4.01it/s]
100%|██████████| 1/1 [00:00<00:00,  2.99it/s]
100%|██████████| 1/1 [00:00<00:00,  3.57it/s]
100%|██████████| 1/1 [00:00<00:00,  3.97it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  3.90it/s]
100%|██████████| 1/1 [00:00<00:00,  2.93it/s]
100%|██████████| 1/1 [00:00<00:00,  2.80it/s]
100%|██████████| 1/1 [00:00<00:00,  3.09it/s]
100%|██████████| 1/1 [00:00<00:00,  1.10it/s]
100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  1.83it/s]
100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
100%|██████████| 1/1 [00:00<00:00,  2.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
100%|██████████| 1/1 [00:00<00:00,  4.98it/s]
100%|██████████| 1/1 [00:00<00:00,  2.31it/s]
100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  3.03it/s]
100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.79it/s]
100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
100%|██████████| 1/1 [00:00<00:00,  5.07it/s]
100%|██████████| 1/1 [00:00<00:00,  5.87it/s]
100%|██████████| 1/1 [00:00<00:00,  5.62it/s]
100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
100%|██████████| 1/1 [00:00<00:00,  5.70it/s]
100%|██████████| 1/1 [00:00<00:00,  5.26it/s]
100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
100%|██████████| 1/1 [00:00<00:00,  5.95it/s]
100%|██████████| 1/1 [00:00<00:00,  5.70it/s]
100%|██████████| 1/1 [00:00<00:00,  4.86it/s]
100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  2.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  2.93it/s]
100%|██████████| 1/1 [00:00<00:00,  5.27it/s]
100%|██████████| 1/1 [00:00<00:00,  4.93it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.29it/s]
100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  4.77it/s]
100%|██████████| 1/1 [00:00<00:00,  5.04it/s]
100%|██████████| 1/1 [00:00<00:00,  4.94it/s]
100%|██████████| 1/1 [00:00<00:00,  5.23it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  4.81it/s]
100%|██████████| 1/1 [00:00<00:00,  3.10it/s]
100%|██████████| 1/1 [00:00<00:00,  5.51it/s]
100%|██████████| 1/1 [00:00<00:00,  3.58it/s]
100%|██████████| 1/1 [00:00<00:00,  5.49it/s]
100%|██████████| 1/1 [00:00<00:00,  4.34it/s]
100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
100%|██████████| 1/1 [00:00<00:00,  5.21it/s]
100%|██████████| 1/1 [00:00<00:00,  5.18it/s]
100%|██████████| 1/1 [00:00<00:00,  5.03it/s]
100%|██████████| 1/1 [00:00<00:00,  4.68it/s]
100%|██████████| 1/1 [00:00<00:00,  4.83it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  1.96it/s]
100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
100%|██████████| 1/1 [00:00<00:00,  5.04it/s]
100%|██████████| 1/1 [00:00<00:00,  5.29it/s]
100%|██████████| 1/1 [00:00<00:00,  5.09it/s]
100%|██████████| 1/1 [00:00<00:00,  5.01it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.26it/s]
100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
100%|██████████| 1/1 [00:00<00:00,  4.79it/s]
100%|██████████| 1/1 [00:00<00:00,  4.91it/s]
100%|██████████| 1/1 [00:01<00:00,  1.22s/it]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  3.35it/s]
100%|██████████| 1/1 [00:00<00:00,  2.80it/s]
100%|██████████| 1/1 [00:00<00:00,  3.02it/s]
100%|██████████| 1/1 [00:00<00:00,  2.96it/s]
100%|██████████| 1/1 [00:00<00:00,  2.75it/s]
100%|██████████| 1/1 [00:00<00:00,  3.11it/s]
100%|██████████| 1/1 [00:00<00:00,  3.39it/s]
100%|██████████| 1/1 [00:00<00:00,  3.59it/s]
100%|██████████| 1/1 [00:00<00:00,  1.89it/s]
100%|██████████| 1/1 [00:00<00:00,  3.87it/s]
100%|██████████| 1/1 [00:00<00:00,  2.97it/s]
100%|██████████| 1/1 [00:00<00:00,  2.96it/s]
100%|██████████| 1/1 [00:00<00:00,  4.00it/s]
100%|██████████| 1/1 [00:00<00:00,  2.80it/s]
100%|██████████| 1/1 [00:00<00:00,  3.31it/s]
100%|██████████| 1/1 [00:00<00:00,  4.50it/s]
100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  4.73it/s]
100%|██████████| 1/1 [00:00<00:00,  4.55it/s]
100%|██████████| 1/1 [00:00<00:00,  5.20it/s]
100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.813939,1.000000,0.926587,1.000000,0.935132,1
2,Random Forest,0.758126,0.979371,0.937979,1.000000,0.918869,2
1,Decision Tree,0.638303,0.903519,0.932290,1.000000,0.868528,3
4,MLP,0.566040,0.639520,0.936897,1.000000,0.785614,4
3,XGBoost,0.665821,0.000000,0.936444,1.000000,0.650566,5

====================================================================================================
REPETITION 17/20 | seed=58
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
100%|██████████| 1/1 [00:00<00:00,  5.34it/s]
100%|██████████| 1/1 [00:00<00:00,  2.26it/s]
100%|██████████| 1/1 [00:00<00:00,  5.79it/s]
100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  5.39it/s]
100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.57it/s]
100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
100%|██████████| 1/1 [00:00<00:00,  6.46it/s]
100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
100%|██████████| 1/1 [00:00<00:00,  6.22it/s]
100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
100%|██████████| 1/1 [00:00<00:00,  6.46it/s]
100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
100%|██████████| 1/1 [00:00<00:00,  6.67it/s]
100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
100%|██████████| 1/1 [00:00<00:00,  4.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.82it/s]
100%|██████████| 1/1 [00:00<00:00,  4.47it/s]
100%|██████████| 1/1 [00:00<00:00,  1.48it/s]
100%|██████████| 1/1 [00:00<00:00,  4.94it/s]
100%|██████████| 1/1 [00:00<00:00,  4.25it/s]
100%|██████████| 1/1 [00:00<00:00,  4.35it/s]
100%|██████████| 1/1 [00:00<00:00,  4.54it/s]
100%|██████████| 1/1 [00:00<00:00,  4.89it/s]
100%|██████████| 1/1 [00:00<00:00,  5.07it/s]
100%|██████████| 1/1 [00:00<00:00,  4.53it/s]
100%|██████████| 1/1 [00:00<00:00,  4.81it/s]
100%|██████████| 1/1 [00:00<00:00,  4.81it/s]
100%|██████████| 1/1 [00:00<00:00,  4.97it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
100%|██████████| 1/1 [00:00<00:00,  5.95it/s]
100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
100%|██████████| 1/1 [00:00<00:00,  6.33it/s]
100%|██████████| 1/1 [00:00<00:00,  6.22it/s]
100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
100%|██████████| 1/1 [00:00<00:00,  4.18it/s]
100%|██████████| 1/1 [00:00<00:00,  4.51it/s]
100%|██████████| 1/1 [00:00<00:00,  4.39it/s]
100%|██████████| 1/1 [00:00<00:00,  4.36it/s]
100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
100%|██████████| 1/1 [00:00<00:00,  4.94it/s]
100%|██████████| 1/1 [00:00<00:00,  4.93it/s]
100%|██████████| 1/1 [00:00<00:00,  4.27it/s]
100%|██████████| 1/1 [00:00<00:00,  3.88it/s]
100%|██████████| 1/1 [00:00<00:00,  4.16it/s]
100%|██████████| 1/1 [00:00<00:00,  4.20it/s]
100%|██████████| 1/1 [00:00<00:00,  4.42it/s]
100%|██████████| 1/1 [00:00<00:00,  4.12it/s]
100%|██████████| 1/1 [00:00<00:00,  4.66it/s]
100%|██████████| 1/1 [00:00<00:00,  4.92it/s]
100%|██████████| 1/1 [00:00<00:00,  4.59it/s]
100%|██████████| 1/1 [00:00<00:00,  1.06it/s]
100%|██████████| 1/1 [00:00<00:00,  4.40it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
100%|██████████| 1/1 [00:00<00:00,  6.54it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  1.31it/s]
100%|██████████| 1/1 [00:05<00:00,  5.48s/it]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.50it/s]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.50it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.44it/s]
100%|██████████| 1/1 [00:00<00:00,  2.66it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.36it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  1.91it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  1.92it/s]
100%|██████████| 1/1 [00:00<00:00,  1.79it/s]
100%|██████████| 1/1 [00:00<00:00,  1.82it/s]
100%|██████████| 1/1 [00:00<00:00,  1.68it/s]
100%|██████████| 1/1 [00:01<00:00,  1.06s/it]
100%|██████████| 1/1 [00:00<00:00,  1.80it/s]
100%|██████████| 1/1 [00:00<00:00,  1.68it/s]
100%|██████████| 1/1 [00:00<00:00,  2.14it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.58it/s]
100%|██████████| 1/1 [00:00<00:00,  2.50it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:01<00:00,  1.27s/it]
100%|██████████| 1/1 [00:00<00:00,  2.45it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.42it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  5.45it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
100%|██████████| 1/1 [00:00<00:00,  5.62it/s]
100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
100%|██████████| 1/1 [00:00<00:00,  3.86it/s]
100%|██████████| 1/1 [00:00<00:00,  4.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.73it/s]
100%|██████████| 1/1 [00:00<00:00,  5.62it/s]
100%|██████████| 1/1 [00:00<00:00,  5.65it/s]
100%|██████████| 1/1 [00:00<00:00,  3.46it/s]
100%|██████████| 1/1 [00:00<00:00,  3.46it/s]
100%|██████████| 1/1 [00:00<00:00,  2.93it/s]
100%|██████████| 1/1 [00:00<00:00,  2.66it/s]
100%|██████████| 1/1 [00:00<00:00,  3.32it/s]
100%|██████████| 1/1 [00:00<00:00,  3.12it/s]
100%|██████████| 1/1 [00:00<00:00,  2.74it/s]
100%|██████████| 1/1 [00:00<00:00,  2.69it/s]
100%|██████████| 1/1 [00:00<00:00,  3.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.13it/s]
100%|██████████| 1/1 [00:00<00:00,  2.85it/s]
100%|██████████| 1/1 [00:00<00:00,  2.91it/s]
100%|██████████| 1/1 [00:00<00:00,  3.42it/s]
100%|██████████| 1/1 [00:00<00:00,  3.58it/s]
100%|██████████| 1/1 [00:00<00:00,  5.60it/s]
100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
100%|██████████| 1/1 [00:00<00:00,  4.92it/s]
100%|██████████| 1/1 [00:00<00:00,  4.98it/s]
100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
100%|██████████| 1/1 [00:00<00:00,  5.51it/s]
100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
100%|██████████| 1/1 [00:00<00:00,  5.50it/s]
100%|██████████| 1/1 [00:00<00:00,  4.96it/s]
100%|██████████| 1/1 [00:00<00:00,  5.29it/s]
100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
100%|██████████| 1/1 [00:00<00:00,  5.49it/s]
100%|██████████| 1/1 [00:00<00:00,  5.23it/s]
100%|██████████| 1/1 [00:00<00:00,  5.03it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
100%|██████████| 1/1 [00:02<00:00,  2.06s/it]
100%|██████████| 1/1 [00:00<00:00,  5.42it/s]
100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  3.01it/s]
100%|██████████| 1/1 [00:00<00:00,  2.29it/s]
100%|██████████| 1/1 [00:00<00:00,  3.30it/s]
100%|██████████| 1/1 [00:00<00:00,  2.85it/s]
100%|██████████| 1/1 [00:00<00:00,  4.05it/s]
100%|██████████| 1/1 [00:00<00:00,  1.98it/s]
100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
100%|██████████| 1/1 [00:00<00:00,  5.15it/s]
100%|██████████| 1/1 [00:00<00:00,  5.18it/s]
100%|██████████| 1/1 [00:00<00:00,  2.97it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.39it/s]
100%|██████████| 1/1 [00:00<00:00,  5.23it/s]
100%|██████████| 1/1 [00:00<00:00,  5.04it/s]
100%|██████████| 1/1 [00:00<00:00,  4.80it/s]
100%|██████████| 1/1 [00:00<00:00,  5.18it/s]
100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  5.26it/s]
100%|██████████| 1/1 [00:00<00:00,  5.01it/s]
100%|██████████| 1/1 [00:00<00:00,  4.58it/s]
100%|██████████| 1/1 [00:00<00:00,  5.29it/s]
100%|██████████| 1/1 [00:00<00:00,  4.86it/s]
100%|██████████| 1/1 [00:00<00:00,  4.94it/s]
100%|██████████| 1/1 [00:00<00:00,  3.46it/s]
100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
100%|██████████| 1/1 [00:00<00:00,  4.97it/s]
100%|██████████| 1/1 [00:00<00:00,  5.00it/s]
100%|██████████| 1/1 [00:00<00:00,  5.43it/s]
100%|██████████| 1/1 [00:00<00:00,  4.52it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  5.23it/s]
100%|██████████| 1/1 [00:00<00:00,  4.48it/s]
100%|██████████| 1/1 [00:00<00:00,  5.20it/s]
100%|██████████| 1/1 [00:00<00:00,  4.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
100%|██████████| 1/1 [00:00<00:00,  5.02it/s]
100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
100%|██████████| 1/1 [00:00<00:00,  5.17it/s]
100%|██████████| 1/1 [00:00<00:00,  4.80it/s]
100%|██████████| 1/1 [00:00<00:00,  5.02it/s]
100%|██████████| 1/1 [00:00<00:00,  5.22it/s]
100%|██████████| 1/1 [00:00<00:00,  1.97it/s]
100%|██████████| 1/1 [00:00<00:00,  4.83it/s]
100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
100%|██████████| 1/1 [00:00<00:00,  3.90it/s]
100%|██████████| 1/1 [00:00<00:00,  3.28it/s]
100%|██████████| 1/1 [00:00<00:00,  2.79it/s]
100%|██████████| 1/1 [00:00<00:00,  2.11it/s]
100%|██████████| 1/1 [00:00<00:00,  3.70it/s]
100%|██████████| 1/1 [00:00<00:00,  3.94it/s]
100%|██████████| 1/1 [00:00<00:00,  4.01it/s]
100%|██████████| 1/1 [00:00<00:00,  3.61it/s]
100%|██████████| 1/1 [00:00<00:00,  3.73it/s]
100%|██████████| 1/1 [00:00<00:00,  2.90it/s]
100%|██████████| 1/1 [00:00<00:00,  2.92it/s]
100%|██████████| 1/1 [00:00<00:00,  3.12it/s]
100%|██████████| 1/1 [00:00<00:00,  3.00it/s]
100%|██████████| 1/1 [00:00<00:00,  3.90it/s]
100%|██████████| 1/1 [00:00<00:00,  3.65it/s]
100%|██████████| 1/1 [00:00<00:00,  4.02it/s]
100%|██████████| 1/1 [00:00<00:00,  3.84it/s]
100%|██████████| 1/1 [00:00<00:00,  3.61it/s]
100%|██████████| 1/1 [00:00<00:00,  4.02it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.740870,1.000000,0.932918,1.000000,0.918447,1
2,Random Forest,0.723064,0.964173,0.936873,1.000000,0.906027,2
1,Decision Tree,0.607441,0.923118,0.938179,1.000000,0.867185,3
4,MLP,0.565189,0.591138,0.938265,1.000000,0.773648,4
3,XGBoost,0.656895,0.000000,0.936591,1.000000,0.648372,5

====================================================================================================
REPETITION 18/20 | seed=59
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  6.68it/s]
100%|██████████| 1/1 [00:00<00:00,  5.97it/s]
100%|██████████| 1/1 [00:00<00:00,  5.97it/s]
100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
100%|██████████| 1/1 [00:00<00:00,  5.73it/s]
100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
100%|██████████| 1/1 [00:00<00:00,  2.69it/s]
100%|██████████| 1/1 [00:00<00:00,  2.12it/s]
100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
100%|██████████| 1/1 [00:00<00:00,  6.20it/s]
100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
100%|██████████| 1/1 [00:00<00:00,  5.95it/s]
100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
100%|██████████| 1/1 [00:00<00:00,  6.31it/s]
100%|██████████| 1/1 [00:00<00:00,  5.82it/s]
100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
100%|██████████| 1/1 [00:00<00:00,  6.35it/s]
100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
100%|██████████| 1/1 [00:00<00:00,  3.96it/s]
100%|██████████| 1/1 [00:00<00:00,  4.55it/s]
100%|██████████| 1/1 [00:00<00:00,  4.80it/s]
100%|██████████| 1/1 [00:00<00:00,  5.07it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
100%|██████████| 1/1 [00:00<00:00,  6.33it/s]
100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
100%|██████████| 1/1 [00:00<00:00,  6.51it/s]
100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
100%|██████████| 1/1 [00:00<00:00,  5.99it/s]
100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
100%|██████████| 1/1 [00:00<00:00,  6.07it/s]
100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
100%|██████████| 1/1 [00:00<00:00,  6.67it/s]
100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
100%|██████████| 1/1 [00:00<00:00,  4.39it/s]
100%|██████████| 1/1 [00:00<00:00,  4.20it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  4.78it/s]
100%|██████████| 1/1 [00:00<00:00,  4.98it/s]
100%|██████████| 1/1 [00:00<00:00,  4.29it/s]
100%|██████████| 1/1 [00:00<00:00,  5.01it/s]
100%|██████████| 1/1 [00:00<00:00,  2.29it/s]
100%|██████████| 1/1 [00:00<00:00,  4.41it/s]
100%|██████████| 1/1 [00:00<00:00,  3.98it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.50it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:01<00:00,  1.70s/it]
100%|██████████| 1/1 [00:00<00:00,  1.73it/s]
100%|██████████| 1/1 [00:00<00:00,  1.85it/s]
100%|██████████| 1/1 [00:01<00:00,  1.92s/it]
100%|██████████| 1/1 [00:00<00:00,  2.44it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
100%|██████████| 1/1 [00:00<00:00,  2.46it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.24it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
100%|██████████| 1/1 [00:00<00:00,  2.43it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.46it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  1.28it/s]
100%|██████████| 1/1 [00:00<00:00,  2.68it/s]
100%|██████████| 1/1 [00:00<00:00,  2.20it/s]
100%|██████████| 1/1 [00:00<00:00,  2.14it/s]
100%|██████████| 1/1 [00:00<00:00,  2.42it/s]
100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  1.81it/s]
100%|██████████| 1/1 [00:00<00:00,  1.84it/s]
100%|██████████| 1/1 [00:00<00:00,  1.75it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  2.29it/s]
100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
100%|██████████| 1/1 [00:00<00:00,  3.35it/s]
100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
100%|██████████| 1/1 [00:00<00:00,  5.01it/s]
100%|██████████| 1/1 [00:00<00:00,  5.65it/s]
100%|██████████| 1/1 [00:00<00:00,  5.01it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.42it/s]
100%|██████████| 1/1 [00:00<00:00,  4.99it/s]
100%|██████████| 1/1 [00:00<00:00,  5.50it/s]
100%|██████████| 1/1 [00:00<00:00,  5.62it/s]
100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
100%|██████████| 1/1 [00:00<00:00,  5.50it/s]
100%|██████████| 1/1 [00:00<00:00,  5.52it/s]
100%|██████████| 1/1 [00:00<00:00,  5.03it/s]
100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
100%|██████████| 1/1 [00:00<00:00,  5.03it/s]
100%|██████████| 1/1 [00:00<00:00,  5.43it/s]
100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
100%|██████████| 1/1 [00:00<00:00,  3.49it/s]
100%|██████████| 1/1 [00:00<00:00,  5.62it/s]
100%|██████████| 1/1 [00:00<00:00,  5.50it/s]
100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
100%|██████████| 1/1 [00:00<00:00,  5.52it/s]
100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.42it/s]
100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
100%|██████████| 1/1 [00:00<00:00,  5.07it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.56it/s]
100%|██████████| 1/1 [00:00<00:00,  5.15it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]
100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
100%|██████████| 1/1 [00:00<00:00,  4.88it/s]
100%|██████████| 1/1 [00:00<00:00,  5.21it/s]
100%|██████████| 1/1 [00:00<00:00,  5.12it/s]
100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
100%|██████████| 1/1 [00:00<00:00,  5.17it/s]
100%|██████████| 1/1 [00:00<00:00,  4.63it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.09it/s]
100%|██████████| 1/1 [00:00<00:00,  4.77it/s]
100%|██████████| 1/1 [00:00<00:00,  5.17it/s]
100%|██████████| 1/1 [00:00<00:00,  4.43it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
100%|██████████| 1/1 [00:00<00:00,  5.26it/s]
100%|██████████| 1/1 [00:00<00:00,  5.13it/s]
100%|██████████| 1/1 [00:00<00:00,  4.48it/s]
100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
100%|██████████| 1/1 [00:00<00:00,  5.22it/s]
100%|██████████| 1/1 [00:00<00:00,  4.97it/s]
100%|██████████| 1/1 [00:00<00:00,  5.09it/s]
100%|██████████| 1/1 [00:00<00:00,  4.88it/s]
100%|██████████| 1/1 [00:00<00:00,  5.04it/s]
100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.17it/s]
100%|██████████| 1/1 [00:00<00:00,  4.48it/s]
100%|██████████| 1/1 [00:00<00:00,  5.04it/s]
100%|██████████| 1/1 [00:00<00:00,  5.12it/s]
100%|██████████| 1/1 [00:00<00:00,  4.74it/s]
100%|██████████| 1/1 [00:00<00:00,  3.34it/s]
100%|██████████| 1/1 [00:00<00:00,  2.94it/s]
100%|██████████| 1/1 [00:00<00:00,  3.64it/s]
100%|██████████| 1/1 [00:00<00:00,  3.67it/s]
100%|██████████| 1/1 [00:00<00:00,  2.74it/s]
100%|██████████| 1/1 [00:00<00:00,  3.01it/s]
100%|██████████| 1/1 [00:00<00:00,  3.19it/s]
100%|██████████| 1/1 [00:00<00:00,  3.53it/s]
100%|██████████| 1/1 [00:00<00:00,  3.33it/s]
100%|██████████| 1/1 [00:00<00:00,  3.08it/s]
100%|██████████| 1/1 [00:00<00:00,  3.01it/s]
100%|██████████| 1/1 [00:00<00:00,  2.68it/s]
100%|██████████| 1/1 [00:00<00:00,  3.06it/s]
100%|██████████| 1/1 [00:00<00:00,  1.45it/s]
100%|██████████| 1/1 [00:00<00:00,  4.43it/s]
100%|██████████| 1/1 [00:00<00:00,  4.96it/s]
100%|██████████| 1/1 [00:00<00:00,  5.06it/s]
100%|██████████| 1/1 [00:00<00:00,  4.73it/s]
100%|██████████| 1/1 [00:00<00:00,  3.75it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
100%|██████████| 1/1 [00:00<00:00,  4.45it/s]
100%|██████████| 1/1 [00:00<00:00,  5.00it/s]
100%|██████████| 1/1 [00:00<00:00,  4.98it/s]
100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
100%|██████████| 1/1 [00:00<00:00,  4.84it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.784026,1.000000,0.937259,1.000000,0.930321,1
2,Random Forest,0.737505,0.963305,0.942626,1.000000,0.910859,2
1,Decision Tree,0.613926,0.979751,0.931884,1.000000,0.881390,3
4,MLP,0.570911,0.607054,0.941264,1.000000,0.779807,4
3,XGBoost,0.663990,0.000000,0.942048,1.000000,0.651509,5

====================================================================================================
REPETITION 19/20 | seed=60
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  6.51it/s]
100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
100%|██████████| 1/1 [00:00<00:00,  5.89it/s]
100%|██████████| 1/1 [00:00<00:00,  6.22it/s]
100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
100%|██████████| 1/1 [00:00<00:00,  6.61it/s]
100%|██████████| 1/1 [00:00<00:00,  6.17it/s]
100%|██████████| 1/1 [00:00<00:00,  6.67it/s]
100%|██████████| 1/1 [00:00<00:00,  2.10it/s]
100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
100%|██████████| 1/1 [00:00<00:00,  5.91it/s]
100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
100%|██████████| 1/1 [00:00<00:00,  2.00it/s]
100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
100%|██████████| 1/1 [00:00<00:00,  6.33it/s]
100%|██████████| 1/1 [00:00<00:00,  6.51it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.92it/s]
100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
100%|██████████| 1/1 [00:00<00:00,  5.97it/s]
100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.91it/s]
100%|██████████| 1/1 [00:00<00:00,  6.51it/s]
100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.62it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.63it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.51it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.31it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.36it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  1.98it/s]
100%|██████████| 1/1 [00:01<00:00,  1.67s/it]
100%|██████████| 1/1 [00:00<00:00,  1.69it/s]
100%|██████████| 1/1 [00:00<00:00,  1.39it/s]
100%|██████████| 1/1 [00:00<00:00,  1.18it/s]
100%|██████████| 1/1 [00:00<00:00,  1.95it/s]
100%|██████████| 1/1 [00:00<00:00,  2.55it/s]
100%|██████████| 1/1 [00:00<00:00,  2.31it/s]
100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
100%|██████████| 1/1 [00:00<00:00,  2.29it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.30it/s]
100%|██████████| 1/1 [00:00<00:00,  2.21it/s]
100%|██████████| 1/1 [00:00<00:00,  1.61it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
100%|██████████| 1/1 [00:00<00:00,  5.52it/s]
100%|██████████| 1/1 [00:00<00:00,  5.73it/s]
100%|██████████| 1/1 [00:00<00:00,  5.57it/s]
100%|██████████| 1/1 [00:00<00:00,  4.81it/s]
100%|██████████| 1/1 [00:00<00:00,  5.42it/s]
100%|██████████| 1/1 [00:00<00:00,  5.51it/s]
100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.42it/s]
100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
100%|██████████| 1/1 [00:00<00:00,  5.49it/s]
100%|██████████| 1/1 [00:00<00:00,  4.98it/s]
100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.61it/s]
100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
100%|██████████| 1/1 [00:00<00:00,  3.10it/s]
100%|██████████| 1/1 [00:00<00:00,  3.10it/s]
100%|██████████| 1/1 [00:00<00:00,  3.01it/s]
100%|██████████| 1/1 [00:01<00:00,  1.05s/it]
100%|██████████| 1/1 [00:00<00:00,  2.68it/s]
100%|██████████| 1/1 [00:00<00:00,  3.43it/s]
100%|██████████| 1/1 [00:00<00:00,  2.71it/s]
100%|██████████| 1/1 [00:00<00:00,  2.82it/s]
100%|██████████| 1/1 [00:00<00:00,  3.04it/s]
100%|██████████| 1/1 [00:00<00:00,  2.87it/s]
100%|██████████| 1/1 [00:00<00:00,  3.08it/s]
100%|██████████| 1/1 [00:00<00:00,  4.88it/s]
100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
100%|██████████| 1/1 [00:00<00:00,  4.87it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
100%|██████████| 1/1 [00:00<00:00,  2.15it/s]
100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
100%|██████████| 1/1 [00:00<00:00,  4.99it/s]
100%|██████████| 1/1 [00:00<00:00,  4.88it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  4.55it/s]
100%|██████████| 1/1 [00:00<00:00,  4.94it/s]
100%|██████████| 1/1 [00:00<00:00,  5.23it/s]
100%|██████████| 1/1 [00:00<00:00,  4.69it/s]
100%|██████████| 1/1 [00:00<00:00,  5.17it/s]
100%|██████████| 1/1 [00:00<00:00,  3.94it/s]
100%|██████████| 1/1 [00:00<00:00,  3.42it/s]
100%|██████████| 1/1 [00:00<00:00,  3.42it/s]
100%|██████████| 1/1 [00:00<00:00,  3.00it/s]
100%|██████████| 1/1 [00:00<00:00,  3.28it/s]
100%|██████████| 1/1 [00:00<00:00,  3.23it/s]
100%|██████████| 1/1 [00:00<00:00,  2.82it/s]
100%|██████████| 1/1 [00:00<00:00,  3.75it/s]
100%|██████████| 1/1 [00:00<00:00,  3.53it/s]
100%|██████████| 1/1 [00:00<00:00,  4.77it/s]
100%|██████████| 1/1 [00:00<00:00,  3.15it/s]
100%|██████████| 1/1 [00:00<00:00,  3.17it/s]
100%|██████████| 1/1 [00:00<00:00,  3.54it/s]
100%|██████████| 1/1 [00:00<00:00,  1.48it/s]
100%|██████████| 1/1 [00:00<00:00,  3.15it/s]
100%|██████████| 1/1 [00:00<00:00,  3.12it/s]
100%|██████████| 1/1 [00:00<00:00,  3.38it/s]
100%|██████████| 1/1 [00:00<00:00,  3.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.06it/s]
100%|██████████| 1/1 [00:00<00:00,  5.21it/s]
100%|██████████| 1/1 [00:00<00:00,  1.83it/s]
100%|██████████| 1/1 [00:00<00:00,  4.98it/s]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  4.92it/s]
100%|██████████| 1/1 [00:00<00:00,  4.75it/s]
100%|██████████| 1/1 [00:00<00:00,  2.17it/s]
100%|██████████| 1/1 [00:00<00:00,  1.24it/s]
100%|██████████| 1/1 [00:00<00:00,  5.34it/s]
100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
100%|██████████| 1/1 [00:00<00:00,  4.76it/s]
100%|██████████| 1/1 [00:00<00:00,  4.56it/s]
100%|██████████| 1/1 [00:00<00:00,  5.29it/s]
100%|██████████| 1/1 [00:00<00:00,  4.98it/s]
100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
100%|██████████| 1/1 [00:00<00:00,  5.06it/s]
100%|██████████| 1/1 [00:00<00:00,  4.73it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  2.12it/s]
100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
100%|██████████| 1/1 [00:00<00:00,  4.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.05it/s]
100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
100%|██████████| 1/1 [00:00<00:00,  4.98it/s]
100%|██████████| 1/1 [00:00<00:00,  5.06it/s]
100%|██████████| 1/1 [00:00<00:00,  4.74it/s]
100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
100%|██████████| 1/1 [00:00<00:00,  4.87it/s]
100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
100%|██████████| 1/1 [00:00<00:00,  4.29it/s]
100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
100%|██████████| 1/1 [00:00<00:00,  5.04it/s]
100%|██████████| 1/1 [00:00<00:00,  2.06it/s]
100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
100%|██████████| 1/1 [00:00<00:00,  4.50it/s]
100%|██████████| 1/1 [00:00<00:00,  4.80it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.786695,1.000000,0.921566,1.000000,0.927065,1
2,Random Forest,0.750226,0.954782,0.924947,1.000000,0.907489,2
1,Decision Tree,0.676351,0.908153,0.932987,1.000000,0.879373,3
4,MLP,0.546713,0.544603,0.936685,1.000000,0.757000,4
3,XGBoost,0.670654,0.000000,0.936278,1.000000,0.651733,5

====================================================================================================
REPETITION 20/20 | seed=61
====================================================================================================
   Logistic Regression

100%|██████████| 1/1 [00:00<00:00,  4.75it/s]
100%|██████████| 1/1 [00:00<00:00,  5.00it/s]
100%|██████████| 1/1 [00:00<00:00,  1.46it/s]
100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
100%|██████████| 1/1 [00:00<00:00,  5.00it/s]
100%|██████████| 1/1 [00:00<00:00,  4.80it/s]
100%|██████████| 1/1 [00:00<00:00,  4.21it/s]
100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
100%|██████████| 1/1 [00:00<00:00,  1.46it/s]
100%|██████████| 1/1 [00:00<00:00,  5.99it/s]
100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
100%|██████████| 1/1 [00:00<00:00,  2.14it/s]
100%|██████████| 1/1 [00:00<00:00,  5.99it/s]
100%|██████████| 1/1 [00:00<00:00,  5.91it/s]
100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
100%|██████████| 1/1 [00:00<00:00,  6.51it/s]
100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
100%|██████████| 1/1 [00:00<00:00,  5.98it/s]
100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
100%|██████████| 1/1 [00:00<00:00,  3.36it/s]
100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
100%|██████████| 1/1 [00:00<00:00,  6.68it/s]
100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
100%|██████████| 1/1 [00:00<00:00,  6.22it/s]
100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
100%|██████████| 1/1 [00:00<00:00,  6.61it/s]
100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
100%|██████████| 1/1 [00:00<00:00,  6.20it/s]
100%|██████████| 1/1 [00:00<00:00,  6.26it/s]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
100%|██████████| 1/1 [00:00<00:00,  4.77it/s]
100%|██████████| 1/1 [00:00<00:00,  6.41it/s]

   Decision Tree

100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
100%|██████████| 1/1 [00:00<00:00,  6.06it/s]
100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
100%|██████████| 1/1 [00:00<00:00,  5.57it/s]
100%|██████████| 1/1 [00:00<00:00,  3.39it/s]
100%|██████████| 1/1 [00:00<00:00,  6.17it/s]
100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
100%|██████████| 1/1 [00:00<00:00,  6.12it/s]
100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
100%|██████████| 1/1 [00:00<00:00,  5.79it/s]
100%|██████████| 1/1 [00:00<00:00,  1.11it/s]
100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
100%|██████████| 1/1 [00:00<00:00,  6.12it/s]
100%|██████████| 1/1 [00:00<00:00,  1.22it/s]
100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
100%|██████████| 1/1 [00:00<00:00,  6.27it/s]
100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
100%|██████████| 1/1 [00:00<00:00,  5.82it/s]
100%|██████████| 1/1 [00:00<00:00,  5.22it/s]
100%|██████████| 1/1 [00:00<00:00,  4.63it/s]
100%|██████████| 1/1 [00:00<00:00,  4.50it/s]
100%|██████████| 1/1 [00:00<00:00,  4.51it/s]

   Random Forest

100%|██████████| 1/1 [00:00<00:00,  2.57it/s]
100%|██████████| 1/1 [00:05<00:00,  5.54s/it]
100%|██████████| 1/1 [00:00<00:00,  2.44it/s]
100%|██████████| 1/1 [00:00<00:00,  1.71it/s]
100%|██████████| 1/1 [00:00<00:00,  1.74it/s]
100%|██████████| 1/1 [00:00<00:00,  1.81it/s]
100%|██████████| 1/1 [00:00<00:00,  1.68it/s]
100%|██████████| 1/1 [00:00<00:00,  1.74it/s]
100%|██████████| 1/1 [00:00<00:00,  1.77it/s]
100%|██████████| 1/1 [00:00<00:00,  1.70it/s]
100%|██████████| 1/1 [00:00<00:00,  1.72it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
100%|██████████| 1/1 [00:00<00:00,  2.43it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
100%|██████████| 1/1 [00:00<00:00,  2.45it/s]
100%|██████████| 1/1 [00:00<00:00,  2.58it/s]
100%|██████████| 1/1 [00:00<00:00,  2.40it/s]
100%|██████████| 1/1 [00:00<00:00,  2.53it/s]
100%|██████████| 1/1 [00:00<00:00,  2.46it/s]
100%|██████████| 1/1 [00:00<00:00,  2.44it/s]
100%|██████████| 1/1 [00:00<00:00,  2.50it/s]
100%|██████████| 1/1 [00:00<00:00,  2.43it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.49it/s]
100%|██████████| 1/1 [00:00<00:00,  2.50it/s]
100%|██████████| 1/1 [00:00<00:00,  2.36it/s]
100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
100%|██████████| 1/1 [00:00<00:00,  2.50it/s]

   XGBoost

100%|██████████| 1/1 [00:00<00:00,  5.89it/s]
100%|██████████| 1/1 [00:00<00:00,  4.30it/s]
100%|██████████| 1/1 [00:00<00:00,  4.57it/s]
100%|██████████| 1/1 [00:00<00:00,  3.02it/s]
100%|██████████| 1/1 [00:00<00:00,  2.50it/s]
100%|██████████| 1/1 [00:00<00:00,  3.05it/s]
100%|██████████| 1/1 [00:00<00:00,  2.84it/s]
100%|██████████| 1/1 [00:00<00:00,  3.56it/s]
100%|██████████| 1/1 [00:00<00:00,  3.35it/s]
100%|██████████| 1/1 [00:00<00:00,  3.30it/s]
100%|██████████| 1/1 [00:00<00:00,  2.81it/s]
100%|██████████| 1/1 [00:00<00:00,  2.78it/s]
100%|██████████| 1/1 [00:00<00:00,  2.71it/s]
100%|██████████| 1/1 [00:00<00:00,  2.87it/s]
100%|██████████| 1/1 [00:00<00:00,  3.37it/s]
100%|██████████| 1/1 [00:00<00:00,  3.74it/s]
100%|██████████| 1/1 [00:00<00:00,  3.11it/s]
100%|██████████| 1/1 [00:00<00:00,  5.62it/s]
100%|██████████| 1/1 [00:00<00:00,  5.15it/s]
100%|██████████| 1/1 [00:00<00:00,  5.17it/s]
100%|██████████| 1/1 [00:00<00:00,  5.54it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
100%|██████████| 1/1 [00:00<00:00,  4.87it/s]
100%|██████████| 1/1 [00:00<00:00,  5.45it/s]
100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
100%|██████████| 1/1 [00:01<00:00,  1.69s/it]
100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
100%|██████████| 1/1 [00:00<00:00,  1.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
100%|██████████| 1/1 [00:00<00:00,  5.54it/s]
100%|██████████| 1/1 [00:00<00:00,  5.50it/s]
100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.45it/s]
100%|██████████| 1/1 [00:00<00:00,  5.61it/s]
100%|██████████| 1/1 [00:00<00:00,  5.23it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:01<00:00,  1.94s/it]
100%|██████████| 1/1 [00:00<00:00,  5.48it/s]

   MLP

100%|██████████| 1/1 [00:00<00:00,  5.46it/s]
100%|██████████| 1/1 [00:00<00:00,  4.77it/s]
100%|██████████| 1/1 [00:00<00:00,  5.15it/s]
100%|██████████| 1/1 [00:00<00:00,  5.23it/s]
100%|██████████| 1/1 [00:00<00:00,  4.90it/s]
100%|██████████| 1/1 [00:00<00:00,  5.20it/s]
100%|██████████| 1/1 [00:00<00:00,  4.32it/s]
100%|██████████| 1/1 [00:00<00:00,  4.72it/s]
100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
100%|██████████| 1/1 [00:00<00:00,  5.35it/s]
100%|██████████| 1/1 [00:00<00:00,  5.15it/s]
100%|██████████| 1/1 [00:00<00:00,  4.36it/s]
100%|██████████| 1/1 [00:00<00:00,  4.81it/s]
100%|██████████| 1/1 [00:00<00:00,  5.06it/s]
100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
100%|██████████| 1/1 [00:00<00:00,  5.09it/s]
100%|██████████| 1/1 [00:00<00:00,  4.72it/s]
100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
100%|██████████| 1/1 [00:00<00:00,  4.75it/s]
100%|██████████| 1/1 [00:00<00:00,  4.69it/s]
100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
100%|██████████| 1/1 [00:00<00:00,  4.62it/s]
100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
100%|██████████| 1/1 [00:00<00:00,  4.76it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
100%|██████████| 1/1 [00:00<00:00,  4.83it/s]
100%|██████████| 1/1 [00:00<00:00,  4.72it/s]
100%|██████████| 1/1 [00:00<00:00,  5.13it/s]
100%|██████████| 1/1 [00:00<00:00,  4.83it/s]
100%|██████████| 1/1 [00:00<00:00,  5.18it/s]
100%|██████████| 1/1 [00:00<00:00,  5.12it/s]
100%|██████████| 1/1 [00:00<00:00,  4.65it/s]
100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
100%|██████████| 1/1 [00:00<00:00,  5.09it/s]
100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
100%|██████████| 1/1 [00:00<00:00,  4.73it/s]
100%|██████████| 1/1 [00:00<00:00,  3.69it/s]
100%|██████████| 1/1 [00:00<00:00,  3.43it/s]
100%|██████████| 1/1 [00:01<00:00,  1.97s/it]
100%|██████████| 1/1 [00:00<00:00,  3.15it/s]
100%|██████████| 1/1 [00:00<00:00,  2.71it/s]
100%|██████████| 1/1 [00:00<00:00,  3.02it/s]
100%|██████████| 1/1 [00:00<00:00,  3.20it/s]
100%|██████████| 1/1 [00:00<00:00,  1.63it/s]
100%|██████████| 1/1 [00:00<00:00,  3.45it/s]
100%|██████████| 1/1 [00:00<00:00,  3.56it/s]
100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
100%|██████████| 1/1 [00:00<00:00,  4.15it/s]
100%|██████████| 1/1 [00:00<00:00,  5.29it/s]

,model_name,fidelity_score,stability_score,actionability_score,regulatory_alignment_score,ees_score,ees_rank
0,Logistic Regression,0.807045,0.988255,0.933614,1.000000,0.932228,1
2,Random Forest,0.753646,0.961940,0.937742,1.000000,0.913332,2
1,Decision Tree,0.683952,1.000000,0.929184,1.000000,0.903284,3
4,MLP,0.557747,0.646475,0.933337,1.000000,0.784390,4
3,XGBoost,0.687699,0.000000,0.938726,1.000000,0.656606,5

Rows: 100 Expected: 100

In [11]:
# 8. Reviewer-facing uncertainty summary
rows=[]
for mid,g in uncertainty_results_df.groupby('model_id'):
    rows.append({'dataset_name':DATASET_NAME,'dataset_label':DATASET_LABEL,'model_id':mid,'model_name':g.model_name.iloc[0],'n_repetitions':len(g),
      'mean_fidelity':g.fidelity_score.mean(),'sd_fidelity':g.fidelity_score.std(ddof=1),
      'mean_stability':g.stability_score.mean(),'sd_stability':g.stability_score.std(ddof=1),
      'mean_actionability':g.actionability_score.mean(),'sd_actionability':g.actionability_score.std(ddof=1),
      'mean_regulatory_alignment':g.regulatory_alignment_score.mean(),'sd_regulatory_alignment':g.regulatory_alignment_score.std(ddof=1),
      'mean_ees':g.ees_score.mean(),'sd_ees':g.ees_score.std(ddof=1),'ees_empirical_2_5_pct':g.ees_score.quantile(.025),'ees_empirical_97_5_pct':g.ees_score.quantile(.975),'ees_min':g.ees_score.min(),'ees_max':g.ees_score.max(),
      'mean_rank':g.ees_rank.mean(),'median_rank':g.ees_rank.median(),'best_rank':g.ees_rank.min(),'worst_rank':g.ees_rank.max(),'rank_1_count':int((g.ees_rank==1).sum()),'rank_1_frequency':float((g.ees_rank==1).mean())})
uncertainty_summary_df=pd.DataFrame(rows).sort_values(['mean_rank','mean_ees'],ascending=[True,False]).reset_index(drop=True)
display(uncertainty_summary_df)

,dataset_name,dataset_label,model_id,model_name,n_repetitions,mean_fidelity,sd_fidelity,mean_stability,sd_stability,mean_actionability,sd_actionability,mean_regulatory_alignment,sd_regulatory_alignment,mean_ees,sd_ees,ees_empirical_2_5_pct,ees_empirical_97_5_pct,ees_min,ees_max,mean_rank,median_rank,best_rank,worst_rank,rank_1_count,rank_1_frequency
0,german_credit,German Credit,logistic_regression,Logistic Regression,20,0.793213,0.021900,0.996699,0.009598,0.934147,0.005423,1.000000,0.000000,0.931015,0.006759,0.916150,0.940257,0.914072,0.940628,1.000000,1.000000,1,1,20,1.000000
1,german_credit,German Credit,random_forest,Random Forest,20,0.752303,0.016796,0.957168,0.012270,0.939170,0.004640,1.000000,0.000000,0.912160,0.005886,0.901183,0.921414,0.900387,0.922661,2.000000,2.000000,2,2,0,0.000000
2,german_credit,German Credit,decision_tree,Decision Tree,20,0.668383,0.033794,0.941155,0.051928,0.938640,0.007273,1.000000,0.000000,0.887045,0.016959,0.859397,0.910195,0.853907,0.912428,3.000000,3.000000,3,3,0,0.000000
3,german_credit,German Credit,mlp,MLP,20,0.572319,0.017946,0.612815,0.064642,0.939086,0.003391,1.000000,0.000000,0.781055,0.017850,0.753608,0.811768,0.750766,0.813759,4.000000,4.000000,4,4,0,0.000000
4,german_credit,German Credit,xgboost,XGBoost,20,0.682328,0.017741,0.000000,0.000000,0.943131,0.004426,1.000000,0.000000,0.656365,0.004927,0.649414,0.665466,0.648372,0.669239,5.000000,5.000000,5,5,0,0.000000

In [12]:
# 9. Rank distributions and champions
rank_distribution_df=uncertainty_results_df.groupby(['model_id','model_name','ees_rank']).size().rename('count').reset_index(); rank_distribution_df['frequency']=rank_distribution_df['count']/N_REPETITIONS
champions_df=uncertainty_results_df[uncertainty_results_df.ees_rank==1][['repetition','split_seed','model_id','model_name','ees_score']].sort_values(['repetition','model_id']).reset_index(drop=True)
champion_frequency_df=champions_df.groupby(['model_id','model_name']).size().rename('rank_1_count').reset_index(); champion_frequency_df['rank_1_frequency']=champion_frequency_df['rank_1_count']/N_REPETITIONS
champion_frequency_df=champion_frequency_df.sort_values('rank_1_frequency',ascending=False).reset_index(drop=True)
display(champion_frequency_df)

              model_id           model_name  rank_1_count  rank_1_frequency
0  logistic_regression  Logistic Regression            20          1.000000

In [13]:
# 10. Save outputs
for df,name,folder in [
 (uncertainty_results_df,'ees_uncertainty_repetition_results.csv',DATASETS_PATH),
 (uncertainty_results_df,'ees_uncertainty_repetition_results.csv',TABLES_PATH),
 (uncertainty_summary_df,'ees_uncertainty_summary.csv',TABLES_PATH),
 (rank_distribution_df,'ees_rank_distribution_long.csv',TABLES_PATH),
 (champions_df,'ees_split_champions.csv',TABLES_PATH),
 (champion_frequency_df,'ees_rank1_frequency.csv',TABLES_PATH),
 (run_log_df,'ees_uncertainty_run_log.csv',LOGS_PATH)]: save_df(df,name,folder)
excel=TABLES_PATH/'ees_uncertainty_rank_stability_outputs.xlsx'
with pd.ExcelWriter(excel,engine='openpyxl') as w:
    uncertainty_results_df.to_excel(w,sheet_name='repetition_results',index=False); uncertainty_summary_df.to_excel(w,sheet_name='uncertainty_summary',index=False); rank_distribution_df.to_excel(w,sheet_name='rank_distribution',index=False); champion_frequency_df.to_excel(w,sheet_name='rank1_frequency',index=False); run_log_df.to_excel(w,sheet_name='run_log',index=False)
manifest={'dataset_name':DATASET_NAME,'dataset_label':DATASET_LABEL,'notebook':'09_00_ees_uncertainty_rank_stability.ipynb','run_timestamp':datetime.now().isoformat(),'n_repetitions':N_REPETITIONS,'test_size':TEST_SIZE,'stratified':True,'split_seeds':SPLIT_SEEDS,'models':list(make_models(42).keys()),'primary_ees_weights':EES_WEIGHTS,'regulatory_alignment_score':REGULATORY_ALIGNMENT_SCORE,'interpretation_note':'The 2.5th-97.5th percentile range is an empirical uncertainty interval across overlapping repeated stratified holdouts, not an independent-sample population confidence interval.'}
with open(LOGS_PATH/'ees_uncertainty_rank_stability_manifest.json','w') as f: json.dump(manifest,f,indent=4)
print('Saved:',excel)

Saved: /content/drive/MyDrive/Master_Research/07_Results/german_credit/09_00_ees_uncertainty_rank_stability/datasets/ees_uncertainty_repetition_results.csv
Saved: /content/drive/MyDrive/Master_Research/07_Results/german_credit/09_00_ees_uncertainty_rank_stability/tables/ees_uncertainty_repetition_results.csv
Saved: /content/drive/MyDrive/Master_Research/07_Results/german_credit/09_00_ees_uncertainty_rank_stability/tables/ees_uncertainty_summary.csv
Saved: /content/drive/MyDrive/Master_Research/07_Results/german_credit/09_00_ees_uncertainty_rank_stability/tables/ees_rank_distribution_long.csv
Saved: /content/drive/MyDrive/Master_Research/07_Results/german_credit/09_00_ees_uncertainty_rank_stability/tables/ees_split_champions.csv
Saved: /content/drive/MyDrive/Master_Research/07_Results/german_credit/09_00_ees_uncertainty_rank_stability/tables/ees_rank1_frequency.csv
Saved: /content/drive/MyDrive/Master_Research/07_Results/german_credit/09_00_ees_uncertainty_rank_stability/logs/ees_uncertainty_run_log.csv
Saved: /content/drive/MyDrive/Master_Research/07_Results/german_credit/09_00_ees_uncertainty_rank_stability/tables/ees_uncertainty_rank_stability_outputs.xlsx

## Reviewer-facing interpretation
Use this analysis together with the existing robustness work: **10-fold stratified CV** addresses predictive robustness; the existing **EES weighting sensitivity** addresses sensitivity to evaluation priorities; this notebook addresses **sampling/split uncertainty in EES components and model ranking**.

Report mean EES, SD, the empirical 2.5th–97.5th percentile interval, mean/median rank, best/worst rank, and rank-1 frequency. Because repeated holdouts overlap in observations, do not describe the 20 repetitions as 20 independent datasets.